# Copyright Notice {#copyright}

The research articles included in this cumulative dissertation have been or will be published in international peer-reviewed journals. Copyright of the text and illustrations lies with the author or authors of the respective chapter(s). The publishers own the exclusive rights to publish or use the text and illustrations for their own purposes. Reprinting any part of this dissertation thesis requires the permission of the copyright holder(s).
The individual contributions of this cumulative thesis have been or will be published (in chronological order) as follows:

Prein, J. C., Kalinke, S., Haun, D. B. M.\*, & Bohn, M.\* (2023). TANGO: A reliable, open-source, browser-based task to assess individual differences in gaze understanding in 3 to 5-year-old children and adults. *Behavior Research Methods, 56*(3), 2469–2485. https://doi.org/10.3758/s13428-023-02159-5

Prein, J. C., Maurits, L., Werwach, A., Haun, D. B. M.,\* & Bohn, M.\* (2024). *Variation in gaze understanding across the life span: A process-level perspective.* PsyArXiv. https://doi.org/10.31234/osf.io/dy73a

Bohn, M.\*, Prein, J. C.\*, Ayikoru, A., Bednarski, F. M., Dzabatou, A., Frank, M. C., Henderson, A. M. E., Isabella, J., Kalbitz, J., Kanngiesser, P., Keşşafoğlu, D., Koymen, B., Manrique-Hernandez, M., Magazi, S., Mújica-Manrique, L., Ohlendorf, J., Olaoba, D., Pieters, W., Pope-Caldwell, S., … Haun, D. (2024). *A universal of human social cognition: Children from 17 communities process gaze in similar ways.* PsyArXiv. https://doi.org/10.31234/osf.io/z3ahv

Prein, J. C., Maurits, L., Werwach, A., Haun, D. B. M., & Bohn, M. (2024). *Variation in gaze following across the life span: A process-level perspective.* PsyArXiv. https://doi.org/10.31234/osf.io/dy73a

&nbsp;

Further articles that were written in the context of this dissertation can be found in the Appendix and have been or will be published as follows (in chronological order):

Schuwerk, T., Kampis, D., Baillargeon, R., Biro, S., Bohn, M., Byers-Heinlein, K., Dörrenberg, S., Fisher, C., Franchin, L., Fulcher, T., Garbisch, I., Geraci, A., Grosse Wiesmann, C., Hamlin, K., Haun, D. B. M., Hepach, R., Hunnius, S., Hyde, D. C., Karman, P., ..., Prein, J., ... Rakoczy, H. (2021). *Action anticipation based on an agent’s epistemic state in toddlers and adults. Child Development* (In-Principle Acceptance of Registered Report Stage 1: Study Design). PsyArXiv. https://doi.org/10.31234/osf.io/x4jbm

Bohn, M., Prein, J. C., Engicht, J., Haun, D., Gagarina, N., & Koch, T. (2023). *PREVIC: An adaptive parent report measure of expressive vocabulary in children between 3 and 8 years of age.* PsyArXiv. https://doi.org/10.31234/osf.io/hvncp

Bohn, M.\*, Prein, J.\*, Koch, T., Bee, R. M., Delikaya, B., Haun, D., & Gagarina, N. (2024). oREV: An item response theory-based open receptive vocabulary task for 3- to 8-year-old children. *Behavior Research Methods, 56*(3), 2595–2605. https://doi.org/10.3758/s13428-023-02169-3

Steffan, A., Zimmer, L., Arias-Trejo, N., Bohn, M., Dal Ben, R., Flores-Coronado, M. A., Franchin, L., Garbisch, I., Grosse Wiesmann, C., Hamlin, J. K., Havron, N., Hay, J. F., Hermansen, T. K., Jakobsen, K. V., Kalinke, S., Ko, E.-S., Kulke, L., Mayor, J., Meristo, M., …, Prein, J., …, Schuwerk, T. (2024). Validation of an open source, remote web-based eye-tracking method (WebGazer) for research in early childhood. *Infancy, 29*(1), 31–55. https://doi.org/10.1111/infa.12564

&nbsp;

\* denotes shared first or last authorship.
