# Abstract {#abstract}

Social cognition enables children to navigate the social world and engage meaningfully with others. 
As they develop, children become increasingly skilled at predicting and interpreting others' mental states\thinspace --\thinspace such as beliefs, desires, and intentions\thinspace --\thinspace and at understanding different perspectives.
The bedrock of many social-cognitive abilities is gaze following: Identifying another's visual focus of attention is valuable for extracting information from the environment and determining the internal states of other agents. The emergence of gaze following has been thoroughly studied on a group level in children from the Global North. Yet we know little about individual-level and cross-cultural variation. This is problematic because many developmental theories emphasize the role of social interaction in the development of social cognition\thinspace --\thinspace and the frequency and characteristics of social interactions vary substantially across individuals and cultures. This dissertation aims to highlight the prevalence and importance of variation in social cognition based on the example of gaze following. In four studies, we have designed a new gaze following task and applied it to capture individual- and community-level variation in this core social-cognitive ability. 

Study I focused on the development and psychometric assessment of a new task, the TANGO (Task for Assessing iNdividual Differences in Gaze understanding-Open). An animated interactive picture book asked participants to locate a balloon with the help of an agent's gaze cue. A spatial layout allowed for a discrete and continuous measure of participants’ imprecision in locating the gaze of the agent. We implemented a new interactive web application that works across devices and enables supervised and unsupervised in-person and remote testing. We found substantial individual differences in a child (*N*\thinspace=\thinspace 387 from Leipzig, Germany) and an adult (*N*\thinspace =\thinspace 236, international remote) sample. Good psychometric properties, in the form of high internal consistency and test-retest reliability, indicated highly systematic variation. Relationships with family-level variables and children's language abilities underline the validity of the task. Together, the results show how the TANGO is a reliable and valid tool to assess individual differences in gaze following.

Study II applied the TANGO to answer three research questions focusing on individual differences in gaze following.
First, we aimed to assess how gaze following develops across the lifespan. For this, we examined imprecision in gaze following in children, teenagers, and adults (*N*\thinspace =\thinspace 478 3- to 19-year-olds from Leipzig, Germany, and *N*\thinspace =\thinspace 240 20- to 80-year-old international, remotely tested adults). During preschool years, children became increasingly precise in gaze following and reached adult-like performance at around ten years of age. Young adults reached the highest precision levels, which slightly declined toward old age. Across all age groups, participants showed individual differences. 
Second, we were interested in how people cognitively process gaze cues and how different imprecision levels in gaze following could be explained. With the help of a computational cognitive model, we conceptualized individual differences in gaze following on a process level (*N*\thinspace =\thinspace 60 3- to 5-year-olds and *N*\thinspace =\thinspace 50 adults). Participants were modeled to observe the agent's pupil location within the eye and estimate the resulting pupil angles and gaze vectors. This inferential estimation process was assumed to be noisy. Individual differences and the development of gaze following were described as varying levels in the precision to estimate pupil angles. A model comparison with two alternative models and a signature pattern in the data yielded strong evidence for the proposed gaze model. 
Third, we intended to study how other (social-) cognitive abilities relate to gaze following. We experimentally tested the model's assumption describing gaze following as a form of social vector estimation (*N*\thinspace =\thinspace 102 4- to 5-year-olds). Individuals' gaze-following abilities correlated with their precision in non-social vector estimation and visual perspective-taking. Other Theory of Mind tasks did not correlate. These findings suggest that gaze following relies on attention to social as well as spatial components.

Study III aimed at examining the universality and variability of gaze following and to broaden our perspective beyond samples coming from the Global North. We presented the largest cross-cultural study on children's gaze following abilities to date (*N*\thinspace =\thinspace 1377): We studied 2.5- to 11-year-olds from 17 different urban/rural communities in Argentina, China, the Republic of the Congo, Germany, India, Mexico, Namibia, Nigeria, New Zealand, Sambia, Türkiye, the UK, Uganda, and the USA. Across communities, we found similar substantial developmental gains: With increasing age, children became more precise in locating the gaze focus of another agent. Absolute differences in imprecision levels could be partially explained by children's familiarity with the data collection device (tablet/touchscreen). In all communities, we found the same signature pattern in the data, and comparisons to alternative models provided strong evidence for the previously proposed gaze model. Despite existing individual- and community-level variation in observable behavior, this speaks for a universal mechanism in how children follow gaze.

Study IV describes the design process of the TANGO-CC, the cross-cultural gaze following task used in Study III. We provided an open-source website and tutorial for researchers to adapt the TANGO-CC to their needs (e.g., selecting language and stimuli). Most importantly, we further aimed to assess how the psychometric properties of the TANGO(-CC) generalize across diverse communities. While we previously established the task's validity and reliability in one community from the Global North (Leipzig, Germany; Study 1), we re-analyzed the cross-cultural data set of Study III. We found individual differences across communities and within-community variation outweighed between-community variation. Split-half reliability estimates for each community were satisfactory. These findings indicated the TANGO-CC's suitability for cross-cultural research. 

Taken together, this dissertation takes an innovative, extensive, multifaceted perspective on gaze following and the cognitive processes behind it. It highlights how combining individual differences, cross-cultural research, and formal modeling will enable us to explore the development and structure of our core social-cognitive processes in greater detail. By openly providing all materials and data, we aim to foster further research in this direction and encourage the scientific community to rethink variation in social cognition.
