# Zusammenfassung {#zusammenfassung}

Soziale Kognition ermöglicht es Kindern, sich in der sozialen Welt zurechtzufinden und angemessen mit anderen zu interagieren. Im Laufe ihrer Entwicklung werden Kinder immer geschickter darin, die mentalen Zustände anderer - wie Überzeugungen, Wünsche und Absichten - vorherzusagen, zu interpretieren und unterschiedliche Perspektiven zu verstehen. Die Grundlage vieler sozial-kognitiver Fähigkeiten ist die Blickverfolgung: Den visuellen Aufmerksamkeitsfokus eines Gegenübers zu identifizieren ist wegweisend, um Informationen aus der Umwelt und über die mentalen Zustände anderer zu gewinnen. Die Blickverfolgung ist auf Gruppenebene bei Kindern aus dem Globalen Norden gründlich untersucht. Jedoch wissen wir nur wenig über individuelle und kulturübergreifende Unterschiede. Dies ist problematisch, da viele Entwicklungstheorien die Rolle der sozialen Interaktion bei der Entwicklung sozialer Kognition betonen und die Häufigkeit und Merkmale sozialer Interaktionen zwischen Individuen und Kulturen erheblich variieren. Diese Dissertation soll die Bedeutsamkeit von Variation in der sozialen Kognition am Beispiel der Blickverfolgung aufzeigen. In vier Studien haben wir eine neue Aufgabe zur Blickverfolgung entwickelt und angewandt, um Variation in dieser zentralen sozial-kognitiven Fähigkeit auf individueller und Gemeinschaftsebene zu erfassen.

Studie I befasste sich mit der Entwicklung und psychometrischen Überprüfung der neuen Aufgabe, dem TANGO (Task for Assessing iNdividual Differences in Gaze understanding-Open). Ein animiertes interaktives Bilderbuch forderte die Teilnehmenden auf, einen Luftballon zu finden, in dem sie der Blickrichtung eines Anderen folgten. Durch ein räumliches Layout konnten wir die Ungenauigkeit von Teilnehmenden in der Blickverfolgung diskret und kontinuierlich messen. Dafür haben wir eine neue interaktive Web-Anwendung implementiert, die geräteübergreifend funktioniert und Datenerhebungen beaufsichtigt vor Ort und unbeaufsichtigt unterwegs ermöglicht. Wir fanden erhebliche individuelle Unterschiede in einer Kinder- (*N*\thinspace=\thinspace 387 aus Leipzig, Deutschland) und einer Erwachsenenstichprobe (*N*\thinspace =\thinspace 236 international verteilt). Die psychometrischen Eigenschaften, basierend auf interner Konsistenz und Test-Retest-Reliabilität, wiesen auf sehr systematische Variation hin. Zusammenhänge mit Variablen auf familiärer Ebene und sprachlichen Fähigkeiten unterstreichen die Validität der Aufgabe. Insgesamt ist der TANGO ein zuverlässiges und valides Instrument, um individuelle Unterschiede in der Blickverfolgung zu erfassen.

In Studie II haben wir den TANGO auf drei Forschungsfragen angewandt, die sich auf individuelle Unterschiede in der Blickverfolgung konzentrieren. Erstens wollten wir herausfinden, wie sich die Blickverfolgung über die Lebensspanne entwickelt. Zu diesem Zweck untersuchten wir die Ungenauigkeit der Blickverfolgung bei Kindern, Jugendlichen und Erwachsenen (*N*\thinspace =\thinspace 478 3- bis 19-jährige Kinder aus Leipzig, Deutschland und *N*\thinspace =\thinspace 240 20- bis 80-jährige internationale Erwachsene). Im Laufe des Vorschulalters wurden Kinder zunehmend präziser, den Blickrichtungen anderer zu folgen. Junge Erwachsene erreichten die höchste Genauigkeit, die mit zunehmendem Alter leicht abnahmen. Über alle Altersgruppen hinweg zeigten die Teilnehmenden individuelle Unterschiede. Zweitens interessierten wir uns dafür, wie Menschen Blickhinweise kognitiv verarbeiten und wie unterschiedliche Ungenauigkeiten bei der Blickverfolgung erklärt werden können. Mit Hilfe eines kognitiven Computermodells konzeptualisierten wir individuelle Unterschiede bei der Blickverfolgung auf Prozessebene (*N*\thinspace =\thinspace 60 3- bis 5-Jährige und *N*\thinspace =\thinspace 50 Erwachsene). Das Modell nimmt an, dass die Teilnehmenden die Position der Pupille im Auge des Gegenübers beobachten und die daraus resultierenden Pupillenwinkel und Blickvektoren schätzen. Dieser inferentielle Schätzprozess kann fehlerhaft sein. Individuelle Unterschiede und die Altersentwicklung in der Blickverfolgung wurden modelliert durch unterschiedlich genaue Schätzungen der Pupillenwinkel. Durch einen Modellvergleich mit zwei alternativen Modellen und einem Signaturmuster in den Daten konnte das vorgeschlagene Blickmodell klar bestätigt werden. Drittens wollten wir untersuchen, wie andere (sozial-) kognitive Fähigkeiten mit der Blickverfolgung zusammenhängen. Wir testeten experimentell die Modellannahme, die Blickverfolgung als eine Form der sozialen Vektorschätzung beschreibt (*N*\thinspace =\thinspace 102 4- bis 5-Jährige). Die Genauigkeit in der Blickverfolgung korrelierte mit einer nicht-sozialen Vektorschätzaufgabe und der visuellen Perspektivübernahme. Andere Theory-of-Mind-Aufgaben korrelierten nicht. Die Ergebnisse deuten darauf hin, dass die Blickverfolgung von der Aufmerksamkeit auf soziale und räumliche Aspekte abhängt.


Studie III zielte darauf ab, die Universalität und Variabilität der Blickverfolgung zu untersuchen und unsere Perspektive über Stichproben des Globalen Nordens hinaus zu erweitern. Diese Studie stellt die bisher größte kulturübergreifende Studie über Blickverfolgung von Kindern dar (*N*\thinspace =\thinspace 1377): Wir untersuchten 2,5- bis 11-Jährige aus 17 verschiedenen städtischen und ländlichen Gemeinschaften in Argentinien, China, der Republik Kongo, Deutschland, Indien, Mexiko, Namibia, Nigeria, Neuseeland, Sambia, der Türkei, Großbritannien, Uganda und den USA. In allen Gemeinschaften fanden wir ähnliche Entwicklungsabläufe: Mit zunehmendem Alter wurden die Kinder präziser darin, den Aufmerksamkeitsfokus eines Gegenübers zu bestimmen. Die absoluten Unterschiede in der Ungenauigkeit konnten teilweise durch die Vertrautheit der Kinder mit dem Endgerät (Tablet/Touchscreen) erklärt werden. In allen Gemeinschaften fanden wir das gleiche charakteristische Muster in den Daten, und Vergleiche mit alternativen Modellen lieferten starke Evidenz für das zuvor vorgeschlagene kognitive Modell. Trotz vorhandener individueller und gemeinschaftlicher Verhaltensunterschiede spricht dies für einen universellen Prozess, wie Kinder der Blickrichtung anderer folgen.

Studie IV beschreibt den Entwicklungsprozess des TANGO-CC\thinspace --\thinspace der kulturübergreifenden Blickverfolgungsaufgabe, die wir in Studie III verwendet haben. Wir präsentieren eine Open-Source-Web-Anwendung und ein Tutorial für Forschende, damit diese den TANGO-CC an ihre Bedürfnisse anpassen können (z.B. durch die Wahl der Sprache und der Stimuli). Das wichtigste Ziel unserer Studie war es, die psychometrischen Eigenschaften des TANGO(-CC) in verschiedenen Gemeinschaften zu untersuchen. Während wir die Validität und Reliabilität der Aufgabe bereits in einer Gemeinschaft des globalen Nordens (Leipzig, Deutschland; Studie 1) nachgewiesen hatten, analysierten wir die kulturübergreifenden Daten der Studie III daraufhingehend erneut. Wir fanden heraus, dass es in allen Gemeinschaften individuelle Unterschiede gab und dass die Variation innerhalb der Gemeinschaften größer waren als die Variation zwischen den Gemeinschaften. In allen Gemeinschaften fanden wir zufriedenstellende Werte in den Split-Half-Reliabilitätsschätzungen. Diese Ergebnisse zeigen, dass der TANGO-CC in der kulturübergreifenden Forschung angewendet werden kann.

Zusammenfassend bietet diese Dissertation eine innovative und vielschichtige Perspektive auf die Entwicklung der Blickverfolgung und die dahinterstehenden kognitiven Prozesse. Sie hebt hervor, wie die Kombination von individuellen Unterschieden, kulturübergreifender Forschung und formaler Modellierung es uns ermöglichen wird, die Entwicklung und Struktur unserer zentralen sozial-kognitiven Prozesse genauer zu untersuchen. Indem wir all unsere Materialien und Daten offen zur Verfügung stellen, wollen wir weitere Forschung in dieser Richtung fördern und die wissenschaftliche Gemeinschaft dazu ermutigen, Variation in Sozialer Kognition neu zu überdenken.
