\mainmatter

# Introduction {#introduction}
- what makes use human?
- social interactions & communication
- how does that develop? 

## Social Cognition
### What
- Definitions of Social Cognition: not that clear...
- @quesque2024defining
- Expert survey: present results and quick methods, but not in detail

## Gaze Following
### What
- maybe: how relates to joint attention
### Why important
- action coordination
- common ground => word learning
- gafo predicts real-life outcomes (language, school performance)
- open questions: Gustaf paper

## Individual Differences
### What
### Why
- survey: experts expect many soc-cog to vary. general picture: the more complex an ability, the more variation expected
- theory building and testing: what relates with what? how do children develop? understand underlying causes
- intervention and education: relies on ind diff, we need to be able to capture change
- example from comparative work: some researchers focus on what chimps in average do, others focus on the very end of the distribution: what are they capable of?
- cross-cultural variation: not only average from small samples

## Methodological Considerations
### Why is variability interesting? 
### How can we capture variability?

- hard to know which way around: are many researchers not interested in ind diff research questions (e.g., how variables relate to one another) and therefore, do not focus on creating new measurement tools? or rather, they do not want to focus on new measurement tools and therefore, do not focus on ind diff research questions?
- likely, rather lack of tools, because time-consuming, exhausting, not that rewarding (other issues in science system...)
- history of science: often new knowledge & theories through new measurement techniques
- gafo: since years, not a lot of new research questions or methods
- new opportunities through new methods
- traditionally, variation seen as measurement error: only averages, exclude outliers
- does it make sense to question this interpretation? why is variation meaningful?
- many seemingly unrelated issues: replicability crisis, no correlations when theoretically expected, overreliance on Global North samples
- how can we address these issues? maybe for many similar solution, namely robust methods
- what makes a method robust? vali & reli
- but also: to move science forward, collaborative endeveaours are needed. Open science, share the task, so that others can reproduce results and test theories & generalizability
- correlations only as large as the least reliable measure; we correlate lots but rarely know the psychometrics of the tasks

## Goals of this thesis
- we need new measures to capture individual differences in social cognition
- this thesis does so for a fundamental social-cognitive ability: gaze following
- paradigmen shift: here example of one construct how this might be possible
- capture ind diff reliably. check process behind it and related constructs. see whether this is universally applicable
- Preference active behavioral measure. With looking times we don’t know whether we’re measuring surprise attention memory expectations etc. not clear whether impact on real life 
