# Structure of This Dissertation {#structure .unnumbered}

This dissertation is part of an overarching, ongoing project led by Prof. Dr. Manuel Bohn (Leuphana University Lüneburg) and Prof. Dr. Daniel Haun (Max Planck Institute for Evolutionary Anthropology Leipzig). The project aims to create a new task battery for social cognition that will capture individual differences in children from diverse communities. The present thesis details the steps that have already been taken in this endeavor: During my time as a doctoral candidate, we have designed, implemented, and validated the first task of the battery, focusing on the fundamental social-cognitive ability of gaze following.

The present dissertation takes a comprehensive approach to developing the new gaze following paradigm, addressing it both from a theoretical and a methodological perspective. The first part of the [Introduction](#introduction) will focus on the psychological construct(s) underlying gaze following: I will describe the importance of human's social cognition and its milestones during child development. I will continue to elaborate on the construct of gaze following and its developmental milestones. I will end both these sections by considering studies that focus on individual differences and, subsequently, studies conducted cross-culturally. The second part of the [Introduction](#introduction) will focus on the methodological considerations for constructing a new task (battery). I will establish the need for individual differences- and cross-cultural research perspectives, examine existing social cognition measures with regards to this identified need, and propose a potential way forward for measures of social-cognitive development.

The next chapter on the [General Approach](#approach) of this dissertation will describe the aims of the four included publications. I will outline the methodological decisions we made while developing the new gaze following task.

In the [General Discussion](#discussion), I will summarize the findings of the four included studies and highlight their theoretical and methodological contributions to developmental psychology. I will discuss their limitations and provide an outlook for future studies in social cognition, focusing on individual differences and cross-cultural research.
