\mainmatter

# General Introduction {#introduction}

Humans share roughly 90 percent of their DNA with that of cats [@pontius2007initial], and even close to 99 percent match our closest living relatives, the chimpanzees [@waterson2005initial]. In many ways, we are comparable to other mammals: for example, we have eyes, ears, and noses that sensorily perceive the surroundings, and we have a neocortex that processes this information and performs higher-order brain functions like spatial reasoning and motor commands. In other domains, the animal kingdom far exceeds humans' abilities and characteristics. Cheetahs can run up to 120 km/h, and Peregrine falcons reach over 380 km/h when diving for prey. Bats and dolphins use echolocation to navigate in complete darkness. Ocean Sunfish have extraordinary reproductive abilities and can lay up to 300 million eggs at once, and the Greenland Shark can live as long as 400 years. So many other species are faster, produce more offspring, and live longer than humans. Yet, the majority of the Earth's surface gets populated, exploited, and domesticated by mainly *one* mammal: the *Homo sapiens*. Which abilities brought humans to their ecological success? What makes us uniquely human?

In 1977, NASA launched the Voyager 1 and 2 spacecraft with a golden time capsule as a bold interstellar greeting. This Golden Record aimed to present the essence of Earth and humanity to potential extraterrestrial receivers. It included natural sounds, music from different cultures, greetings in 55 languages, and a photographic gallery. Among several pictures of mathematical formulas, scientific diagrams, and planetary constellations, a large proportion of the included photos focused on the most fundamental human experiences. These pictures showed humans hunting and playing music together, eating and arguing at a full dinner table, collaboratively rowing a boat, competitively running against each other in marathons, nursing their children, and teaching them how to write. Strikingly, humans were rarely presented alone. These photographs, attempting to capture a comprehensive snapshot of Earth's environment, focused on humans interacting with each other in social and cultural groups.

Our ability to engage with one another in social interaction and communication has been highlighted in prominent evolutionary and psychological theories [e.g., @dunbar1998social; @henrich2007humans; @henrich2015secreta; @herrmann2010structure;@heyes2012new; @heyes2018cognitive; @tomasello2019becoming; @tomasello2003makes]. Contrary to other mammals that act on others' observable actions, humans pay attention to each others' minds [@slaughter2015theorya], and have been described as "ultra-social primates" [@grossmann2022becoming, p. 1]. We perceive other agents in profoundly different ways than other entities in the world [@rakoczy2022foundations], and "social cues are among the most complex stimuli that the human brain has to process" [@beaudoin2020systematic, p. 14]. We form social bonds [e.g., @bowlby1958nature], live (mostly) cooperatively [e.g., @tomasello2020adaptivea], exchange information, and learn through observing others [e.g., @csibra2009natural]. By relying on these strategies, knowledge and skills could be passed on from generation to generation\thinspace --\thinspace which could not have been acquired by one single individual [@henrich2015secreta]. A seminal paper by @herrmann2007humansa tested the hypothesis that humans have unparalleled social-cognitive abilities and administered a cognitive test battery with 16 different tasks to chimpanzees, orangutans, and 2.5-year-old human infants. Indeed, the results showed that all three groups showed similar cognitive abilities within the physical realm (space, quantities, causality), while human infants outperformed the chimpanzees and orangutans when it came to the social world (social learning, communication, \acr{ToM}). Sociality\thinspace --\thinspace and the cognitive abilities enabling it\thinspace --\thinspace might very well be human's superpower.

In 2013, the importance of social cognition was officially recognized by the standard classification framework for mental disorders in the United States, the \acr{DSM-5} [@americanpsychiatricassociation2013diagnostic], which categorized social cognition as one of six core functional domains that can be affected by a neurocognitive disorder. The number of publications in different psychological domains highlights that many psychologists agree on the importance of social cognition. A quick search on the APA PsycNet (on June 25, 2024, at 17:00 CET) revealed 28,594 results for the search term "social cognition", while only 3,095 results appeared for "spatial cognition" and 95 appeared for "physical cognition".

## Social Cognition {#intro-socialcognition}

### Terminology

So far, I have argued for the importance of human social-cognitive abilities. Before going deeper into the developmental literature on social cognition, I want to clarify the terminology: What is *Social Cognition*? Interestingly, most psychologists do not agree on one accepted definition [@beaudoin2020systematic]. Rather, cynical tongues might say there are as many definitions of social cognition as there are research articles on it. As Ostrom put it in the Handbook of Social Cognition: "I regard single-sentence definitions of social cognition to be slightly offensive […]. It would be more accurate to say that my preferred definition is the entire Handbook of Social Cognition, both this and the first edition combined" [@ostrom1994foreword, p. vii]. Indeed, researchers have argued that the non-specific and heterogeneous vocabulary hinders empirical and theoretical advancement: sometimes, a single concept is described by several different labels (i.e., convergence of meaning), while other concepts share the same label but refer to different constructs (i.e., divergence of meaning) [@quesque2020theoryofmind; @quesque2024defining].

To illuminate what developmental psychologists understand under the term social cognition, we conducted a short expert survey in Autumn/Winter 2020 (see [Appendix C](#appendixC)). We distributed an online questionnaire via personal contacts and emailing lists (e.g., cogdevsoc mailing list), and 100 researchers broadly working in cognitive, comparative, cross-cultural, and/or developmental psychology completed it. First, we asked experts to define social cognition as a psychological construct. Exactly one-third of the sample (33%, n = 33) chose a definition by @glynn2016social: "Social cognition is the process by which actors, at individual or collective levels, decode and encode their social world, using mental models, knowledge structures and cultural understandings to process information, extract meaning and determine appropriate action." (p. 1). The next two most frequently chosen definitions similarly focused on information processing aspects in environments enlivened with other agents ("[...] encompasses all the information-processing mechanisms that underlie how people capture, process, store, and apply information about others to navigate social situations" [@decety2020preface, p. ix] (21%, n = 21); “[…] is concerned with the study of the thought processes, both implicit and explicit, through which humans attain understanding of self, others, and their environment" [@moskowitz2013social, p. 1] (10%, n = 10)). In the next step, we asked experts to name which dimensions they mentioned most often when discussing or writing about social cognition. The dimensions that were chosen by more than half of the experts were beliefs, knowledge, perspective-taking, and intentions. Broadly summarizing, social cognition is often understood as a construct that involves information processing in social environments, with a focus on mental states like beliefs, knowledge, perspectives, and intentions. 

When defining social cognition, a distinction must be made to the term \acr{ToM} (also referred to as mentalizing, folk psychology, or psychological reasoning), one of the most studied research areas in developmental cognitive science [@sabbagh2018replication]. While the terms are sometimes used synonymously, social cognition is the umbrella term encompassing \acr{ToM} [@beaudoin2020systematic; @quesque2024defining]. The term \acr{ToM} was first coined by the primatologists @premack1978does and is defined as the ability to view oneself and others as "rational subjects with individual perspectives on the world" [@rakoczy2022foundations, p. 223]. It describes a system organized around mental states to explain and predict the behavior of agents. In other words, we try to understand actions by representing and attributing percepts, desires, and beliefs to ourselves and others\thinspace --\thinspace summarized by Wellman as follows: "In our everyday thinking we construe people as engaging in acts they *think* will get them what they *want*" [@wellman2013universal, p. 69]. A core concept involved in \acr{ToM} is *meta-representation*: representing the content and manner in which agents represent the world from their perspective [@rakoczy2022foundations]. Meta-representational abilities rely on understanding that mental states hold information independent of the real world. Consequently, individuals need to comprehend that mental states can (1) differ between individuals, (2) conflict with their own mental states, (3) be inaccurate or false, and (4) be aspectual (i.e., objects can be represented under certain characteristics) [@rakoczy2022foundations]. \acr{ToM} has been traditionally viewed as a unitary construct, but recent neurophysiological evidence suggests a multidimensional structure [@fu2023systematicb; @slaughter2003introduction]. @beaudoin2020systematic have, for example, identified seven categories within \acr{ToM}, namely "emotions, desires, intentions, percepts, knowledge, beliefs, and mentalistic understanding of non-literal communication" (p. 5), and @fu2023systematicb have proposed the construct dimensions of cognitive (e.g., beliefs) vs. affective (e.g., emotions), and intra- (i.e., concerning yourself) vs. interpersonal (i.e., concerning other agents). Taken together, \acr{ToM} is a part of social cognition focusing on meta-representation of mental states, while social cognition is the broader construct encompassing all information processing in social environments.

### Developmental Milestones

Human infants do not come into the world already possessing mature social cognition [@tomasello2020adaptivea]. Much of developmental psychology research studies how children acquire the social-cognitive abilities which are needed to become full members of our society.

The development of social cognition starts with social perception: Newborns are preferentially interested in faces and biological motion [@simion2015facea; @simion2008predispositiona]. By two months, infants begin to smile socially and engage in proto-conversational social interactions [@rochat1999emerging]. An understanding of agency and others' intentions follows. For example, six-month-old infants expect that another agent acts in a goal-directed way [@woodward1998infants]. From 9 months onward, infants recognize contingencies in actions and realize they are being imitated [@agnetta2004imitative]. They react differently to similar behaviors if those behaviors have different intentions [e.g., unwilling vs. unable agents, @behne2005unwillinga]. In the second half of the first year, infants can judge the rationality of goal-directed actions [@gergely1995taking]. Fourteen-month-olds imitate other actions in a rational way [@gergely2002rationala]. One-and-a-half-year-olds imitate what an agent intended to do and not what they actually did [@meltzoff1995understanding]. At the same age, children help others by completing their previously failed actions [@warneken2006altruistica]. Children between 18 and 21 months start to perform synchronous imitation, pretend play and recognize themselves in mirrors (touching their own face, not the mirror image) [@nielsen2004pretend].

After this so-called perception-goal psychology emerged in infancy, belief-desire psychology develops [@rakoczy2022foundations]. Around 18 months, children can recognize the subjectivity of desires and their relation to emotion [@repacholi1997earlya]. In their second year of life, children engage in Level I perspective-taking, in which they understand *that* different persons perceive objects differently [@moll2006level]. Level II perspective-taking, which involves *how* other agents perceive objects, emerges one year later, around three years of age [@moll2011perspectivetaking]. At this age, children start to reference mental states by using terms like *want*, *think*, *know*, *pretend*, and *dream* in their utterances [@furrow1992mental; @shatz1983acquisition]. Three-year-olds understand that perceptual access leads to knowledge: they understand that a person who has looked into a box knows its content [@hogrefe1986ignorance]. Most four-year-olds understand that they themselves and other agents can have a \acr{FB} [@gopnik1988childrena; @wimmer1983beliefs; @wellman2001metaanalysis]: they grasp that how an agent acts depends not only on reality itself but also on what the agent believes [@wellman2024theory]. Interestingly, recent non-verbal measures (e.g., violation-of-expectation or anticipatory looking paradigms) have argued that infants as young as 15 months show an understanding of \acr{FB} [@onishi200515monthold; @senju2012spontaneous; @southgate2007action]. However, the replicability, reliability, and validity of these implicit measures have been questioned by others [@dorrenberg2018how; @kulke2018implicit; @sabbagh2018replication] as well as the authors of the original findings [@kampis2021twolab].

In later school years, children master higher-order, recursive \acr{ToM} tasks [@liddle2007higherorder] and start recognizing faux pas [@baron-cohen1999recognition]. Five-year-olds begin to understand ironic speakers, but only nine- to ten-year-olds can accurately distinguish irony and sarcasm [@glenwright2010development].

Taken together, children show very early preferences for social stimuli, develop basic social-cognitive abilities in perception, goal, and intentionality understanding around nine months, and refine these fundamental abilities between one and three years of age. At four to five years, children show more complex, meta-representational understandings of beliefs and desires and refine these, in turn, in the following years to gain a recursive, higher-order \acr{ToM} [@rakoczy2022foundations]. Importantly, many of these established findings rely on group-level averages of children based in the Global North [@nielsen2017persistent]\thinspace --\thinspace these shortcomings will be further discussed in later sections of the present dissertation. 

### Individual Differences

Many decades of research in social cognition have taught us much about developmental milestones and the average age at which children show certain social-cognitive abilities [for a review, see @rakoczy2022foundations, or the section above]. Yet, anyone who has ever interacted with children notices that peers can differ substantially in their abilities. For example, one child could barely understand diverse desires, while another child from the same age group could already identify hidden emotions [@slaughter2015theorya].

*Individual differences* describe the features in which agents vary from one another [@americanpsychologicalassociationindividual]. *Inter*-individual differences focus on the variability *between* children, while *intra*-individual differences focus on the variability *within* the same child. @asendorpf1992stability has argued that inter-individual differences are often interpreted as trait-like characteristics (e.g., personality) that are more or less stable over time, while intra-individual differences might capture state-like characteristics (e.g., motivation) or development within a given construct. The present thesis and the associated publications focus on inter-individual differences, often abbreviated to individual differences.

Studies on individual differences in social cognition mainly focus on the social-cognitive ability in question and its connection to (1) family variables, (2) social behavioral measures, and (3) other cognitive abilities [@slaughter2003introduction]. As a quick summary, children's social-cognitive abilities impact their social lives and real-life outcomes [@hughes2004links; @rakoczy2022foundations]. For example, children with sophisticated social cognition show higher levels of prosocial behavior [@imuta2016theory], peer popularity [@slaughter2015meta], mutual friendships [@fink2015friendlessnessa; @fink2015friends]. High \acr{ToM} scores relate to increased communication abilities like persuasive skills [@slaughter2013can] and academic achievements [@binnie2005tom; @lecce2017theory]. Additionally, some negative, egoistic, and manipulative behaviors, such as lying, deceiving, and bullying, also seem to profit from advanced social-cognitive abilities [@ding2015theoryofminda; @gasser2009competent; @rakoczy2022foundations; @talwar2008social]. In contrast, children who struggle with social cognition might experience challenges in their social competencies. Decreased \acr{ToM} performance has been found in children with language impairments [@nilsson2016theory; @stanzione2014environmental] and atypical developmental pathways, including \acr{ASD} [@baron-cohen2000theorya], attention deficit hyperactivity disorder [@pineda-alhucema2018executiveb], oppositional defiant disorder, mood disorders, eating disorders, or obsessive-compulsive disorder [@korkmaz2011theory; @szamburska-lewandowska2021theory]. Importantly, most of these studies are correlational, so the direction of the cause and effect is often unclear [@slaughter2015theorya].

### Cross-Cultural Research

While the majority of (developmental) psychology research is based on samples from the Global North [@apicella2020weird; @gutchess2023considerationa; @henrich2010weirdesta; @kline2018variation; @thalmayer2021neglecteda], some studies focus on how social and cultural factors influence child development. @wellman2013universal has argued that children's social-cognitive development is a particularly informative domain to assess how people worldwide resemble and differ from one another. Several cross-cultural studies have documented substantial variation in this domain [@miller2018contributions; @wellman2014making], and indeed, @quesque2022does found that country-level differences account for more than one-fifth of the variance in participants' understanding of others' thoughts and emotions. An example comes from @wellman2011sequential, who showed that Chinese children understood \acr{KA} at an earlier age than U.S. American children (who, in turn, understood \acr{DB} earlier). Cultural values (e.g., individualist vs. collectivist) and caregiver-child conversations emphasizing different mental states (e.g., knowing vs. thinking) might explain these differences in the \acr{ToM} sequence [@johnston2002cultural; however, see @ilgaz2022cultural]. Evidence for this hypothesis also comes from a study conducted in New Zealand and Iran by @taumoepeau2019crosscultural who found that child-directed mental state talk was related to children's \acr{ToM}.

An interesting observation has been the so-called *Opacity Doctrine* [@dixson2018scalingb]: communities on remote Pacific islands avoid reasoning or talking about the mental states of others as this is deemed inappropriate and impossible. The inclination to not speculate about others' mental states may influence the onset, developmental trajectory, and/or expression of children's \acr{ToM} abilities. @mayer2013synchronyb found a delayed onset of \acr{FB} understanding in Samoan children, with the majority of children being eight years or older when passing the tasks. Similarly, @dixson2018scalingb found that ni-Vanuatu children, especially in rural areas, passed \acr{FB} tasks later than their Western counterparts.

Despite these documented cross-cultural differences, some studies also revealed similarities in social-cognitive development between diverse communities. For example, @barrett2013early studied early \acr{FB} understanding in three traditional, small-scale, non-Western communities. They found that one- to four-year-old children from Salar (China), Shuar/Colono (Ecuador), and Yasawan (Fiji) communities showed similar response patterns in three spontaneous looking time measures to classical studies conducted in Western communities [@barrett2013early]. @callaghan2005synchrony have shown that children from Canada, Samoa, India, and Peru show similar developmental trajectories in \acr{FB} understanding, with some variations at which specific age the majority of children pass the task.

In sum, the order and timing in which children pass classical \acr{ToM} tasks (i.e., \acr{DD}, \acr{DB}, \acr{KA}, content \acr{FB}, \acr{HE}) vary between different communities, which might rely on differences in large-scale cultural, and small scale family factors [@rakoczy2022foundations]. And yet, "children go from consistently wrong to consistently correct worldwide, typically in the preschool years" [@wellman2024theory]. Still, cross-cultural research constitutes only a small fraction of all articles published on social cognition and often covers only specific aspects like children's \acr{ToM} understanding.

## Gaze Following {#intro-gaze}

This dissertation, with its included publications, focuses on one specific aspect of social cognition: gaze following. I will first introduce why eye gaze is important in social cognition, clarify the terminology used in the field of gaze following, and then present developmental milestones, individual differences, and cross-cultural variation in gaze following.

### Relevance and Functions of Eye Gaze

In contrast to other primates, human eyes have a distinctive morphology: they have (1) a depigmented, white sclera, (2) a large exposition of the sclera compared to the eye outline, (3) a stark color contrast between the sclera, the black pupil, the colored iris, and (4) are elongated in the horizontal direction [@kobayashi1997unique; @kobayashi2001unique]. These characteristics heighten the visibility of gaze direction under visually challenging conditions [@kano2022unique]. Furthermore, the ratio of the visible sclera on each side of the pupil might enable humans to detect gaze direction [@anstis1969perception; @todorovic2006geometrical; @symons2004you]. The *cooperative eye hypothesis* suggests that the morphology of the human eye specifically evolved to facilitate gaze following and thereby, communication and cooperation [@tomasello2007reliance]. Findings consistent with this hypothesis show that humans are quicker and more accurate in judging eye gaze when the sclera is depigmented compared to pigmented [@yorzinski2021sclera]. Additionally, neurotypically developing children and adults (but not children with \acr{ASD}) show a preference for eye stimuli with visible white sclera [@segal2016preferences; @wolf2023fiveyearold].

Eye gaze has a variety of different functions, and the "eyes can both signal and perceive" [@gobel2015dual, p. 359]. As such, developmental theories often highlight the role of gaze as a signal for others' attention and intention [@akhtar2008privileging]. Gaze can be informative for external states and direct attention to specific features in our environment [@emery2000eyes; @frith2008social; @gobel2015dual]. Compared to other cues like head or body orientation, the eyes are a clearer indicator of the attentional focus of another agent [@emery2000eyes].

Additionally, eye gaze can signal intentions to others, like invitations to approach and engage or warnings to retreat [@frith2008social; @gobel2015dual; @shepherd2010following]. Looking into another's eyes can serve as a "window into the mind" [@shepherd2010following, p. 10], allowing a glimpse into their beliefs and desires. Therefore, gaze can signal internal emotional and mental states [@emery2000eyes], and, as such, is foundational for more complex social-cognitive abilities [@shepherd2010following]. For example, following eye gaze facilitates anticipating future actions of an agent [@zohary2022gaze; @friesen2011gaze] and enables people to learn through observation [@frith2007social].

Eye gaze is also relevant for pragmatic and language abilities. Monitoring the eye gaze of a conversational partner enables turn-taking [@degutyte2021role], the formation of common ground [@tomasello2007reliance; @bohn2018common], and learning new words (i.e., labels) by identifying the target object [@macdonald2013eye; @hernik2019infant].

In sum, eye gaze is fundamental for social interaction, communication, collaboration, and cultural and social learning [@emery2000eyes; @rakoczy2022foundations; @frith2012mechanisms; @tomasello2003makes; @bohn2019pervasive; @moore2008development; @hessels2020how].

### Terminology

Several different concepts exist that describe an agent's perception of another's eye gaze [see @akhtar2008privileging; @emery2000eyes; @itakura2004gazefollowing]. I will focus on defining *mutual gaze*, *gaze following*, *gaze alternation*, *joint attention*, and *shared attention* (arranged by (most likely) order of increasing complexity in cognitive processing and intentionality understanding).

Mutual gaze describes the attention of two agents directed to each other [@emery2000eyes]; for example, when a child and their caregiver look at each other. As a form of dyadic gaze, it is considered a sign of social engagement [@akhtar2008privileging].

Gaze following marks the process of identifying the attentional focus of another agent and turning one's gaze in the same direction [@delbianco2019developmental]. For example, gaze following occurs when an agent observes that the others' gaze is not aimed at them and subsequently redirects their attention along the others' line of sight to a specific point in space [@emery2000eyes]. Some studies still refer to gaze following, even when the changes in gaze direction are confounded with simultaneous posture, head, and voice changes [@akhtar2008privileging].

Gaze alternation describes switching between looking at an object and an agent's eyes and is a fundamental component of joint attention [@akhtar2008privileging]. Joint attention, in turn, describes an episode in which one agent (i.e., the initiator) gazes at an object, which causes another agent (i.e., the responder) to align and turn their gaze to the same object [@stephenson2021gaze]. It is similar to gaze following except that the attentional focus is directed at a specific target/object [@emery2000eyes] and, as such, involves a triadic relation ("triadic connectedness", [@bard2021joint]) between two agents and an object [@lee1998children].

A related term to joint attention is shared attention, which has been proposed to include the awareness of the common attentional state of both agents [@emery2000eyes]. Both individuals intentionally establish that they are looking at the same object; for example, by back-checking between the object and the other agent's gaze. However, some researchers use the terms joint and shared attention synonymously [@emery2000eyes], while others argue that joint attention already encompasses the awareness and coordination of shared visual attention [e.g., @tomasello1995joint; @tomasello2022coordinationb; @tomasello1986joint]. 

The present dissertation and the included studies focus on gaze following. Gaze following is often seen as a pre-requisite and first ingredient of a joint attention episode [@moll2011perspectivetaking; @stephenson2021gaze]. Researchers have argued whether gaze following reflects an intentional attribution of mental states toward other agents or whether it serves as a more automatic, implicit precursor of later-developing \acr{ToM} abilities [@carlson2013theory; @baron-cohen1995mindblindness; @gopnik1994changing]. @beaudoin2020systematic categorized "adopting the visual perspective of another person" into the "percepts" category in a \acr{ToM} classification. @moll2011perspectivetaking have argued that joint attention and gaze following could be seen as Level 0 perspective-taking. Regardless of whether or not gaze following is seen as a component of \acr{ToM}, it remains a central cornerstone in social cognition and a developmental precursor of many advanced forms of reasoning about others' minds.

### Developmental Milestones

Children's cognitive abilities related to eye gaze evolve from sensitivity to dyadic social interactions to initiation of triadic interactions, with sensitivity to these interactions preceding their initiation, and dyadic interactions preceding triadic ones [@striano2006social]. Infants as young as three months turn their eyes in the same direction as an adult when the adult turns their head and gaze toward one of two objects [@dentremont1997demonstration; @gredeback2010development]. While this is often considered as the onset of gaze following, infants initially rely more on head than gaze direction [@michel2021effects; @lempers1977development]. @brooks2005development have consequently argued that infants begin to "view others as 'body orienters'" (p. 541) [also see @paulus2016when], before they rely on eye gaze as a significant cue to others' attention.

By the age of one, gaze following becomes more sophisticated [@shepherd2010following]. For example, infants are more likely to follow gaze when the agent's eyes are open versus closed [@brooks2002importance]. They can use gaze (and emotional) cues to predict the next action of another agent [@phillips2002infants]. By 14 months, gaze following is contingent on past experiences with the interaction partner's looks: when another agent had previously acted as a "reliable looker" (i.e., smiling at a container with a toy), infants were more likely to follow gaze behind a barrier than when the agent had previously acted as an "unreliable looker" (i.e., smiling at an empty container) [@chow2008see]. At the same age, infants interpret ostensive eye gaze and pointing as relevant communicative cues for finding a hidden toy [@behne2005oneyearolds]. By 12 to 18 months, infants follow gaze to locations outside their immediate line of sight [@moll200412; @deak2000effects; @butterworth1991minds; @corkum1995development].

Children's abilities develop from understanding dyadic to triadic eye gaze and include responding and initiating joint attention episodes [@lee1998children; @striano2006social]. However, young children might be more oriented toward objects instead of gaze itself [@masangkay1974early] and use another's gaze as a cue for salient objects in their surroundings [@moore1994social; @moore1999gaze]. Consequently, the representation between the looker and target does not necessarily entail a representational understanding of mental states [@doherty2009rapid]: "young children might not represent gaze *as* gaze" (p. 298)", instead they "[...] might view gazing as something similar to touching something" (p. 297).

Gaze following beyond these qualitative milestones in infancy is rarely studied. Some evidence suggests that the explicit and accurate judgment of gaze direction alone\thinspace --\thinspace without confounding head and/or body orientation\thinspace --\thinspace might emerge later in development. Children around three to four years of age only start to reliably interpret the direction of gaze when it is not directly facing them and the joint attention of others [@anderson1997preschoolers; @doherty1999new]. Similarly, @doherty2009rapid found that most two- and three-year-olds performed below/around chance in gaze judgment tasks, while preschool children became more accurate, showing adult-like performance around six years of age. Even with congruent head and eye movements, 4.5-year-olds were only moderately accurate in identifying targets separated by 10° [@butterworth2000how].

In sum, gaze following emerges early in infancy and becomes more sophisticated throughout the first years of life. The explicit and accurate evaluation of eye gaze might develop later in childhood.

### Individual Differences

As with other social-cognitive abilities, variation in children's gaze-following abilities has been documented. An individual's ability to follow gaze has consequences for their real social life, particularly regarding social interactions and communications with others [@carpenter1998social]. The role of gaze following and language abilities has been highlighted by the seminal finding of @brooks2005development, who showed that gaze following at ten months is predictive of children's language abilities at 18 months. Fitting to this result, children who spent more time following an agent's gaze to the target object showed larger vocabularies at 18 months (mediated by children's object processing ability) [@okumura2017individual]. Gaze following has been argued to trigger comprehension of an agent's intentional relations to objects\thinspace --\thinspace "an understanding that may play a critical role in word learning (at least the learning of object labels)" [@akhtar2008privileging, p. 60].

Additionally, gaze following might be related to goal and intention understanding. For example, infants' gaze and point-following abilities in triadic interactions correlate with their ability to recognize imitation; that is, distinguishing whether another agent imitated infants or whether the same object manipulations were mechanically performed (independently of any visible actions by the other agent) [@agnetta2004imitative].

Individual differences in the emergence of gaze following might be predicted by contextual factors in children's social and emotional environment: infants showing a secure attachment style and being raised by mothers with lower levels of maternal postpartum depression showed higher frequencies of gaze following [@astor2020social].

Gaze-following research has also gained substantial traction in clinical research focusing on developmental disorders, especially in \acr{ASD} [@delbianco2019developmental]. One diagnostic criterion for \acr{ASD} is an alteration in non-verbal communication, including the social use of eye contact [@americanpsychiatricassociation2013diagnostic]. @forgeotdarc2017gaze reported that "gaze direction detection was less accurate in autism spectrum disorder than in control participants" (p. 100). Children with \acr{ASD} prioritize head over pupil motion [@mihalache2020perceiving] and show reduced preferential looking times to eye and mouth regions of the face [@constantino2017infant]. While some individuals with \acr{ASD} exhibit no impairment in gaze perception, others may be less inclined to initiate eye contact and joint attention, which might influence the course of social interactions [@stephenson2021gaze].

### Cross-Cultural Research {#intro-gaze-cc}

Few studies have assessed children's gaze-following abilities across diverse communities. One examplary work comes from @callaghan2011early who studied 12- and 17-month-old children from rural Canada (*n*\thinspace =\thinspace 35), Peru (*n*\thinspace =\thinspace 38), and India (*n*\thinspace =\thinspace 65). They examined gaze following in scenarios where an agent turned and gazed either at a toy behind a barrier (experimental condition) or a sticker in front of it (control condition) and assessed whether children crawled behind the barrier. Despite cross-cultural variation in absolute crawling rates, children across communities crawled relatively more frequently towards a barrier when an agent gazed at an object behind it rather than in front of it [@callaghan2011early].

Additionally, @hernik2019infant assessed whether differences in face-to-face interaction influence gaze following (with congruent head orientation) in five- to seven-month-old infants in Vanuatu. While face-to-face interactions are less frequent in Vanuatu than in Western communities, infants showed similar gaze patterns: They followed gaze more when they were communicatively addressed beforehand (by infant-directed speech). The authors conclude that "following of gaze in communicative contexts may be available to human infants from various cultural groups regardless of the frequency of exposure to communicative gaze signals from caregivers" [@hernik2019infant, p. 7].

Other cross-cultural research has focused on mutual eye gaze, joint attention, and the factors influencing these abilities. For example, cross-cultural variation has been documented in how infants are typically held, which naturally affects how likely they engage in face-to-face interactions (see study above) and thereby receive the opportunity to engage in mutual gaze [@akhtar2008privileging]. Kaluli mothers in Papua New Guinea tend to carry infants facing away from them, and infants and caregivers rarely look into each other's eyes [@ochs1984language]. Similarly, mothers from the Gusii community in Kenya focus less on gaze and verbal interactions and more on touch than mothers from Boston, USA [@richman1992culturala]. Interestingly, Gusii mothers might use gaze aversion to calm an infant when they are excited [@dixon1981motherinfant].

@childers2007jointa examined whether children's joint attention abilities were affected by being carried on the caregiver's back. The results suggest similar qualitative and quantitative behavioral patterns in Ngas-speaking infants in Nigeria (though notice the small sample size of 16 participants) as those found in English-speaking infants in the USA, which speaks against a potential effect of the caregivers' carrying style on joint attention [@childers2007jointa]. @moreno2021communicative studied children's social interaction, joint attention, and behavior regulation across three communities in Columbia. They found no between-community differences regarding joint attention. The authors concluded that this speaks for the universality of joint attention, especially given the Wayuú's distinct socioeconomic and cultural characteristics differing from the other two communities [@moreno2021communicative]. In contrast, @gavrilov2012sociocultural found that social-cultural factors (e.g., adherence to traditional values and parental education) influenced Israeli children in their initiation of joint attention.

Taken together, cross-cultural studies on eye gaze are rare\thinspace --\thinspace especially those focusing on "literal" gaze following without other bodily cues or target objects. The existing studies underline similarities in gaze and attention understanding across diverse cultural communities, while some results indicate variation with regards to absolute behavioral differences and the social-environmental factors influencing those.

## Methodological Considerations {#intro-methods}

Thus far, I have highlighted human's social cognition, with a focus on the fundamental ability to follow gaze. I have summarized essential milestones in child development and showcased exemplary studies focusing on individual and cross-cultural differences in these domains. Those studies on the variation between individuals and communities remain an exception: While many studies focus on average developmental trajectories in children from the Global North [@nielsen2017persistent], studies on individual- and community-level variation are still scarce. In this section, I will argue why individual- and community-level variation in social cognition is relevant and deserves more attention. I will then discuss whether currently existing social cognition tasks are able to capture this variation. Finally, I will propose a way forward and highlight which characteristics are desirable and needed for new, innovative tasks to measure individual differences in social cognition across diverse communities.

### Relevance of Individual- and Community-level Variation

Classical cognitive science assumes that human cognition is universal and invariant in its structure [@kroupin2024newtona; @levinson2012originalb]. Consequently, traditional experiments often rely on small sample sizes to inform their theory and give little weight to individual differences. When developmental research questions focus on condition differences or the average age at which children pass a given social-cognitive task, variation between children is often handled by excluding outliers and calculating mean scores. As such, between-group (e.g., condition) differences are highlighted as a sign of genuine cognitive variation, while individual differences are regarded as noise or measurement error [@amir2020crosscultural; @kidd2018individual]. I will argue that we need to question the theoretical and statistical stance that variation between individuals and/or communities equals noise and should be "thrown away".

Why should we care about individual differences? Indeed, many research questions in developmental psychology concern individual differences. A textbook example from developmental psychology is the question of (dis)continuity in development. Do children evolve like a butterfly that goes through distinct stages\thinspace --\thinspace from caterpillar to cocoon to butterfly? Or do they develop similarly to a tree that grows continuously over time [@parnes2022infant, p. 8]? Two historically influential theories of cognitive development highlight the different stances. A classic example of a stage-like developmental theory is Piaget's Theory of Cognitive Development [@piaget1929child; @piaget1936origins; @piaget1954construction; @piaget1964cognitive; @piaget1971theory]. Piaget assumed that children progress through qualitatively different stages in a set universal order (i.e., sensorimotor, preoperational, concrete operational, formal operational), and in each stage, interpret the world differently, with increasing levels of complexity. An example of a gradual process developmental theory is Vygotsky's Sociocultural Theory [@vygotsky1962thought; @vygotsky1978mind; @vygotsky1987thinking]. Vygotsky assumed that change occurs slowly and gradually and that cognitive development is driven by an individual's social interactions and cultural context\thinspace --\thinspace not pre-defined by certain stages. According to this theory, social interaction shapes social cognition. To examine questions concerning the (dis)continuity in development, studies must accurately track children's individual abilities across time. While simple age effects can sometimes serve as a proxy for relevant co-occurring events in development (e.g., school entry), age is not *per se* a causal predictor [@mclean2022noa, p. 3]. Consequently, individual differences studies are a powerful tool to build and test developmental theories and the structure of social cognition [@happe2017structure]. Additionally, individual differences studies are needed to evaluate (clinical or educational) intervention programs. For example, capturing change before and after an intervention helps to examine whether children can be trained to improve their perspective-taking abilities [@zhang2021worse; @ruffman2018variety; @lecce2014promoting].

Why should we care about variation between social, cultural, or linguistic communities? Western communities should not have a unique central place in human psychology, nor should they be seen as the default, norm, or "healthy" standard [@kline2018variation; @mclean2022noa]. Indeed, participants from the Global North or \acr{WEIRD} communities are likely to be outliers of the human species [@henrich2010weirdesta; @apicella2020weird]. Contrary to classical cognitive science implicitly assuming little variation across communities [@henrich2010weirdesta], cross-cultural research can assess how ecological and cultural environments form and shape human cognition. "After all, there is no ecology- or culture-free human" [@amir2020crosscultural, p. 431]. Developmental psychology might especially benefit from a cross-cultural perspective and vice versa: Early childhood is a period of especially sensitive and plastic brain growth, in which children are first fully exposed to ecological and cultural inputs [@haun2015comparativea]. Studying developmental pathways in different communities will allow us to (1) establish a "globally representative developmental science" [@broesch2023roadmap, p. 589], (2) rigorously test the generalizability of theories and their underlying assumptions that were originally developed in one particular culture, (3) explore the universality or variability of (social) cognition, and (4) examine how children's early life experiences structure their core cognitive abilities [@amir2020crosscultural; @apicella2020weird; @broesch2023roadmap; @hughes2014lost; @liebal2018crosscultural; @selcuk2023development].

Why should we combine efforts to study individual and cross-cultural variation? Studying group effects of culture on cognition does not suffice: Any given community consists of a group of individuals. @vogeley2009contextualising stated that "Culture is not a well-defined rigid body of rules that shapes each and every individual of a given culture in a similar, uniform way; instead, it dynamically and continuously interacts with its constituting individuals" (p. 512)" and as such, "culture needs to be considered as a dynamical system of individuals" (p. 511). Participating in culture transforms individuals, and participation of individuals transforms culture itself [@rogoff2003cultural]. Environmental and cultural factors\thinspace --\thinspace on a macro, community level as well as micro, family level\thinspace --\thinspace interact with children's unique developmental trajectories and outcomes [@broesch2023roadmap]. While aggregated measures of experience and cognition may cluster within communities, an individual's developmental trajectory may point in different directions than a group-level comparison [@amir2020crosscultural; @bohn2024understanding; @ilgaz2022cultural]. Between-community differences are restricted in their ability to explain how individuals vary in their behaviors throughout the lifespan. They can hardly describe why, how, and which cultural factors shape it [@amir2020crosscultural]. Cultural factors can cause psychological and behavioral variation in developmental processes both within as well as across communities [@kline2018variation], and indeed, within-group variation often outweighs between-group variation [@amir2020crosscultural]. Consequently, we need to measure and link a child's cognitive development and their daily experiences (i.e., how a child perceives their everyday cultural and ecological environments) on an individual level across different communities [@bohn2024understanding; @gutchess2023considerationa].

In sum, the need for an individual differences perspective on child development is more than evident. Studying individuals from diverse social, cultural, and linguistic communities will broaden the scope with which we can capture children's living conditions and developmental pathways [@bohn2024understanding]. Ultimately, the flexibility of mechanisms in human development and the resulting variation in psychological and behavioral outcomes is "a feature rather than a bug" [@kline2018variation, p. 5].

### Terminology

Before I consider the current state of existing social cognition tasks, I will clarify some relevant terms in this context. First, *variability* and *variation* are important when describing individual differences. The definitions of variability and variation greatly resemble each other according to the APA Dictionary of Psychology [@americanpsychologicalassociationvariability; @americanpsychologicalassociationvariation]. Both terms focus on differences between individuals that can be applied to the behavioral level. As in most developmental literature, the terms variability and variation will be used interchangeably in this work.

The psychometric properties of a task are often assessed by considering its *validity* and *reliability*. *Validity* concerns the truthfulness of a task or the degree to which a task captures what it is designed to measure conceptually [@americanpsychologicalassociationvalidity]. There are several different types of validity. In the context of this work, we focus on *convergent* validity (i.e., the degree to which two tasks that should be theoretically related are indeed related), *predictive* validity (i.e., the degree to which a task relates to other tasks separated by a determined period (= predicting scores in the other task)), and *external* validity (i.e., the degree to which the results of a task can be generalized beyond the original sample). *Reliability* refers to the degree to which a task produces consistent, stable results when repeated again or the degree to which a task is free of random measurement error [@americanpsychologicalassociationreliability]. Two main types of reliability are often assessed when evaluating a given task. *Internal consistency* focuses on the relationship between items in the same task to ensure they measure the same construct. *(Test-) Retest reliability* assesses a task's stability over time and estimates the relationship of the task scores on two different administration occasions (e.g., test day one followed by test day two, three weeks later).

### Existing Social Cognition Tasks

As I have argued, many fundamental research questions in developmental psychology are interested in, or build upon, individual differences. I want to start considering whether existing social cognition and \acr{ToM} tasks are capable of measuring individual differences by reviewing one exemplary study. Longitudinal work by @sodian2016understanding investigated how goals, beliefs, and desires relate to moral \acr{ToM}. They reported that "Contrary to expectations, neither goal encoding nor implicit false belief understanding was correlated with the Mo[ral] \acr{ToM} false belief question" (p. 1227). Two main interpretations of these results come to mind. First, the researchers' hypothesis could simply be incorrect: Potentially, goal encoding and implicit \acr{FB} understanding are not related to moral \acr{ToM}. Alternatively, and more optimistically, the non-existent relationship could be explained by methodological issues. Following this interpretation, the applied tasks could not accurately capture variation between children and, therefore, did not find a relationship between the variables. Interestingly, @sodian2016understanding stated two sentences later: "[...] verbal IQ was positively correlated with almost all the assessed variables" (p. 1227). What could this finding hint at? The task for verbal IQ was\thinspace --\thinspace by definition\thinspace --\thinspace designed to capture individual differences in linguistic intelligence. However, tasks used for correlational analyses need to leave room for individual differences in order to find and correlate them [@siegelman2017measuring].

A classical developmental study paradigm "involves describing a social scenario, sometimes using cartoons or puppets, and then asking test questions about what the protagonists feel, want, or know, or what they will do next" [@slaughter2015theorya, p. 170]. Often, they present children with two objects. For example, the Sally-Anne \acr{FB} task lets children witness how a ball gets moved from a box to a basket while another agent does or does not witness the change of location [@baron-cohen1985does; @wimmer1983beliefs]. Children then get asked where the agent believes the ball to be. Possible responses are (1) the box or (2) the basket. Similarly, in the traditional gaze-following paradigm [e.g., @astor2020social; @gredeback2010development; @byers-heinlein2021development; @ishikawa2022physiological], an agent gazes at a location or toy to her left- or right-hand side. The study outcome measures children's reaching behavior toward the two toys (or, in more recent studies, children's looking times). What becomes apparent is that these common social cognition tasks rely on dichotomous designs: An object is either on the left- or right-hand side and a child can either pass or fail the task. Finally, average scores are calculated, for example, the group-level mean in performance. Often, social cognition measures rely on only one or two trials [@cutting1999theory; @henry2016clinical]. All these characteristics lead to poor measurement accuracy and little sensitivity to individual differences [@beaudoin2020systematic]. An inadequate assessment of an individual's (social) cognition can mask connections between cognitive processes and their underlying factors and overshadow developmental trajectories [@mclean2022noa; @petersen2023reexamining].

To briefly summarize: To assess the (inter)dependence of two cognitive abilities or environmental factors, an individual's score must be measured accurately on both scales. Indeed, the correlation between two tasks cannot be greater than the reliability of each individual task [@devellis2006classical]. In light of this statistical feature, the psychometric properties, especially the validity and reliability of measures, gain importance.

In the last ten years, a handful of articles have reviewed social cognition tasks with regard to their measurement properties. For example, @ziatabarahmadi2015validity conducted a systematic review of comprehensive \acr{ToM} measures for preschool children. Exclusion criteria were single tasks like the classical \acr{FB} task and/or no description of the measure's structure, validity, and reliability. From the originally found 1,237 articles, only eleven measures fulfilled all criteria and were included in the review. Of these eleven measures, six relied on verbal measures, two on a forced choice, and three were filled in by children's caregivers. Only one measure was computerized. All eleven measures were judged to be of moderate or high quality. Yet, even within this set, it was rare that validity (e.g., content, construct, criterion-related, or discriminate validity), test-retest reliability, and internal consistency were all reported.

Another systematic review by @beaudoin2020systematic focused on \acr{ToM} measures (including single tasks) for children aged 0 to 5 years of age. The authors argued that despite much progress has been made to study children's \acr{ToM} understanding, drawing robust conclusions about (a)typical development remains challenging\thinspace --\thinspace mainly because of methodological issues. According to their analysis, social cognition studies rarely report psychometrical information: less than one-fifth of the identified 220 measures had information on their internal consistency, less than one-tenth provided test-retest reliability estimates, and shockingly, even fewer measures had examined the construct validity. More than two-thirds of the study samples solely relied on English-speaking participants, and the majority of measures focused on belief understanding [@beaudoin2020systematic].

The most recent review by @fu2023systematicb systematically listed existing \acr{ToM} tasks for children from 0 to 12 years and categorized them by the captured dimension (cognitive vs. affective, inter- vs. intrapersonal), construct (e.g., knowledge access, diverse beliefs, first-order \acr{FB}), presentation mode (e.g., spoken stories, cartoons, picture sequences, interviews), response mode (e.g., spoken language, multiple choices in words/pictures/objects, actions), underlying test theory (classical test theory vs. \acr{IRT}), and psychometric properties. Similarly to @beaudoin2020systematic, @fu2023systematicb highlighted the over-reliance on tasks measuring children's \acr{FB} understanding. Furthermore, only one-fifth of the 127 included \acr{ToM} tasks reported at least one reliability or validity estimate.

Measures that validly and reliably assess the development of social cognition cross-culturally remain even scarcer [@salhi2023assessing; @quesque2022does; @waschl2022crosscultural]. It has been proposed that due to a lack of culturally appropriate tools, social cognition is one of the most challenging cognitive domains to study in diverse communities [@bourdage2023evaluation; @franzen2021crosscultural].

In a systematic review, @bourdage2023evaluation identified cross-cultural social cognition tasks for adult samples, with a focus on participants from the Global South. Of the eighty-four included studies, 45 focused on \acr{ToM}, and six on general social cognition tasks. Thirty-one tasks were translations, 27 adaptations, 14 cross-cultural assessments, and 12 especially assembled for Global South populations. The authors classified 35 as having low quality, 27 as moderate quality, and 22 as high quality. Measurement quality often suffered under limited validity and reliability assessment and small sample sizes.

While the exact number of identified tasks vary between systematic reviews and depends on their search and inclusion criteria, the overall picture is clear: Developmental social cognition tasks suffer from unknown, underdeveloped, or inadequate psychometric properties [e.g., @hiller2014validity; @hutchins2008false; @mayes1996testretest]. While a vast variety of social cognition and \acr{ToM} tasks exist, few are designed to capture individual-level variation, let alone variation between diverse communities. As @hruschka2020we stated, "We have a long road ahead of us in how we measure the world" (p. 458).

### A Potential Way Forward

*What* psychological research questions we study and *which* communities and individuals we sample might be equally important to *how* or *with what* we measure the psychological construct in question [@barrett2020decidingb; @hruschka2020we]. While the development of new tasks can be time-consuming and cumbersome, a historical perspective on science underlines that this endeavor is nevertheless worthwhile. For instance, the invention of the telescope in the early 17th century revolutionized the field of astronomy by enabling detailed observations of celestial bodies. Galileo Galilei's observations of the uneven surface of the Moon, sunspots, the phases of Venus, and Jupiter’s moons challenged the prevailing geocentric model. They provided the first empirical evidence that the Earth and other planets revolve around the Sun. As this example illustrates, methodological advancements not only increase measurement accuracy but can lead to significant shifts in scientific thought and knowledge.

In the research area of social cognition and/or gaze following, many researchers study (the emergence of) these social-cognitive abilities\thinspace --\thinspace and yet, their work often revolves around similar study designs. New research questions or "groundbreaking" theories remain rare. @astor2022gaze postulated that "Despite a steady stream of publications on the development of gaze following, we would like to argue that scientific progress within the field is slow—that data is produced with a high frequency but without adding substantial advancements to our understanding of the phenomenon under investigation and its long-term development" (p. 192). Methodological evolution could be seen as a promising tool, as "methods can erase variation as well as capture it" [@broesch2023roadmap, p. 593]. A focus on individual- and community-level variation could stimulate the gaze-following literature, challenge existing theories, and open up new research avenues. As @smaldino2019better put it: "If we can’t reliably measure something, it’s hard to build a theory about it. [...] Better methods will help us get the right answers; models and measurements will ensure we ask the right questions" (p. 9).

What characteristics would a new task need to capture individual variation in social cognition? Objective, standardized tasks should be the goal to make a quantitative comparison between individuals possible [@schaafsma2015deconstructing]. As we have seen, a classical developmental research question concerns whether child development happens in stages or in a continuous way [@parnes2022infant]. To answer this (dis)continuity question, we need continuous, as opposed to dichotomous, (1) experimental manipulations and (2) outcome measures [@beaudoin2020systematic]. A continuous experimental manipulation could include several levels of trial/item difficulty and, for example, depict gradual mental states (e.g., differing degrees of knowledge or perceptual access). This might help to move beyond studying the age of first emergence and capture more qualitative differences in social-cognitive development [@slaughter2003introduction]. A continuous outcome measure could, for example, include reaction times, looking behavior, or accuracy in fine-grained action responses. This would have several advantages. First, continuous outcome measures leave room for individuals to vary [@hutchins2008false; @schaafsma2015deconstructing]. Second, it could prevent floor- and ceiling effects in which a considerable percentage of participants cluster around the minimum or maximum available scores. Third, this might, in turn, enable sampling older children and adults to get a more complete picture of social-cognitive development across the lifespan [@hutchins2008false; @slaughter2003introduction].

Importantly, a task's psychometric properties must be examined to test whether variation between participants is genuine or due to arbitrary external factors (i.e., noise). Robust methods would show satisfactory validity and reliability estimates [@beaudoin2020systematic; @fu2023systematicb]. Presenting more than one trial per child (or, in the best case, as many as possible) would increase the precision with which we can estimate a participant's ability level [@siegelman2017measuring]. Additionally, the task could capture more possible response patterns which leads to a better differentiation between individuals. Simultaneously, task duration should be brief to allow large sample sizes (especially important for individual difference studies) [@molleman2019unleashing].

Regarding the construct(s) that a task measures, researchers have argued for including more diverse mental states and not falling into the common pitfall of only testing for \acr{FB} understanding [@beaudoin2020systematic; @fu2023systematicb; @heise2023psychometric; @hiller2014validity]. When designing new tasks, processing demands need to be kept in mind so that children's social-cognitive abilities are not masked by extraneous factors [@setoh2016twoandahalfyearolds]. Artificial experimental setups with academic test questions should be avoided as they might lead to potential pragmatic confusion [@oktay-gur2017children; @rakoczy2020young]. Instead, new tasks should aim to measure how children genuinely apply social cognition within contexts that resemble everyday life situations [@slaughter2003introduction]. @fu2023systematicb recommended that \acr{ToM} tasks should include visual stimuli, such as pictures or videos, and response formats with little language demands to aid children's task understanding and language processing.

For studying the variability or universality of our core social-cognitive abilities across communities, studies need to stop oversampling participants from the Global North and include more diverse communities [@arnett2008neglecteda; @henrich2010weirdesta; @kline2018variation; @krys2024weirda; @lillard1998ethnopsychologies]. To include more communities, tasks must be adaptable to different languages and superficial stimulus appearances [@bourdage2023evaluation]. Furthermore, reliability and validity estimates of a task should be verified in every community as these psychometric properties cannot be generalized from one community to another [@hajduk2020how; @bourdage2023evaluation; @waschl2022crosscultural]. While non-verbal tasks avoid issues of inaccuracies in translation, all stimuli and methods should be assessed as to whether they map to the same psychological constructs, are relevant to the participants of the studied community, and get interpreted in similar ways across communities [@kline2018variation].

@amir2020crosscultural have argued for combining cross-cultural and individual differences work with formal modeling. Formal modeling acts as a promising tool to explain and predict the scale, patterns, and sources of variation in human behavior and reverse-engineer the computational cognitive processes causing them [@amir2020crosscultural; @simmering2010dialogue]. This might also help solve the issue that researchers often interpret uniform behavior as evidence for a universal cognitive mechanism, and behavioral differences as evidence for cultural influences and lack of universality\thinspace --\thinspace without explaining how and which factors generate the psychological and/or behavioral differences [@kline2018variation]. For example, behavioral outcomes might vary in their developmental timing and yet, rely on the same universal mechanisms [@broesch2023roadmap]. Formal models will help to define these underlying cognitive processes. In addition, formal modeling forces researchers to explicitly state assumptions underlying their theories, which leads to testable and novel hypotheses\thinspace --\thinspace ultimately leading to better theories [@simmering2010dialogue; @smaldino2019better]. Studies capturing systematic differences in behavioral outcomes will help us to evaluate a model's predictions [@amir2020crosscultural]. Therefore, models benefit from accurate, reliable, and replicable measures on an individual level [@smaldino2019better].

Methodological advancements do not lead anywhere if they are not shared within the scientific community. @elson2023psychological have argued that psychological tasks are often used only a handful of times\thinspace --\thinspace by the same researcher(s) who designed the task. The reluctance to share one's own tasks and re-use tasks of other researchers hinders cumulative science. As the authors figuratively pointed out, "psychological measures aren't toothbrushes" [@elson2023psychological, p.1]. Therefore, Elson and colleagues call for more transparency and standardization in the psychological tasks we implement and apply. Open science principles will help other researchers to reproduce study results, test their generalizability, and eventually address issues related to the replicability crisis in (developmental) psychology [@opensciencecollaboration2015estimating; @sen2024methodological; @syed2021reproducibility].

As I have argued, the field of developmental psychology would benefit from establishing new tasks to capture individual- and community-level variability in social cognition. The present dissertation aims to implement this paradigm shift and showcases an example of how methodological advancement in the area of social cognition\thinspace --\thinspace more specifically, gaze following\thinspace --\thinspace might be possible. In the following chapter, I will outline the aims and approaches of the four studies included in this dissertation in greater detail.
