# Structure of this Dissertation {-#structure}

This dissertation is embedded in an overarching, still ongoing project led by Prof. Dr. Manuel Bohn (Leuphana University Lüneburg) and Prof. Dr. Daniel Haun (Max Planck Institute for Evolutionary Anthropology Leipzig) that will create a new task battery for social cognition. This task battery aims to capture individual differences in children from diverse communities. The present thesis describes the steps that have already been undertaken in this endeavor: during my time as a doctoral candidate, we have designed, implemented, and validated the first task of the battery. We have decided to focus the first task on one of the most fundamental social-cognitive abilities: gaze following.

The present dissertation seeks to approach the development of the new gaze following paradigm from two sides: from a contentual and from a methodological perspective. The first part of the [Introduction](#introduction) will focus on the psychological construct(s) underlying gaze following: I will describe the importance of human's social cognition and its milestones during child development. I will continue to elaborate on the construct of gaze following and its developmental milestones. I will end both these sections by considering studies that focus on individual differences and, subsequently, studies that were conducted cross-culturally. The second part of the [Introduction](#introduction) will focus on the methodological considerations for constructing a new task battery. I will examine existing social cognition measures, identify common challenges and shortcomings, and establish the need for an individual differences- and cross-cultural research perspective.

The next chapter on the [General Approach](#approach) of this dissertation will focus on our aims to develop a new gaze following measure that tackles these recognized methodological challenges. In the [General Discussion](#discussion) chapter, I will summarize our study findings, discuss their limitations and provide an outlook for future studies in social cognition, focusing on individual differences and cross-cultural research.