# General Approach {#approach}

## Aims of this Dissertation {#aims-general}

The overarching aim of this dissertation is to deepen our understanding of variability in a core social-cognitive ability, namely gaze following. First, I have highlighted calls for better (i.e., valid, reliable, generalizable) social cognition tasks. The projects included in this dissertation show an exemplary way how to close this methodological research gap in the future and try to demonstrate that, even if demanding, methodological advancement is feasible and fruitful. Second, by focusing on an individual differences measure, this dissertation aims to question the conception that variation between participants equals noise and should be disregarded. Third, applying the newly designed gaze following task, I hope to show how cross-cultural individual differences research on social cognition helps us to answer fundamental questions about the development, cognitive processes, and universality of human's extraordinary social-cognitive abilities. In the following, I will outline the role each of the four included studies plays in reaching these overall objectives.

### Aims of Study I {#aims-studyI}

To relate cognitive abilities and external factors to each other, social cognition tasks need to be able to measure individual differences. Tasks that are designed to do so remain rare. This study aimed to approach this issue and described the development and validation of our new gaze following task, the \acr{TANGO}. We have designed a playful study in which participants are asked to locate a balloon. The twist is that the participants cannot see the balloon itself. However, they see how another agent (i.e., pig, monkey, sheep) gazes out of a window, toward the balloon. Participants have to follow the agent's gaze to locate the balloon. We designed two task versions: (1) a discrete version in which the balloon was hidden inside a box, and (2) a continuous version in which the balloon was hidden behind a hedge. The box version was generically created in a way that enabled different numbers of boxes (min. 2, max. 8). Participants' gaze following abilities were measured dichotomously (correct/incorrect) in the discrete box version and continuously in the hedge version (distance between the actual target's location and the participant's estimated location).

[Study I](#studyI) consisted of three main parts. In the first part, we assessed the task's usability in a sample of 3- to 5-year-old children and adults. Children came from Leipzig, Germany, and either completed the study in their kindergartens in a quiet room or remotely at home, with the help of their caregivers. Adults were sampled internationally via a participant recruitment platform and completed the study remotely online. Participants completed the \acr{TANGO} in its discrete box version with 5 (for children) or 8 boxes (for adults) or the continuous hedge version. We assessed whether the \acr{TANGO} captured individual differences and whether data collection mode (i.e., remotely vs. in-person) influenced children's performance. In the second part, we aimed to assess whether these individual differences were reliable. We repeated data collection two weeks after the initial session and estimated retest-reliability and internal consistency. In the third part, we attempted to measure the validity of the \acr{TANGO}: For its construct validity, we explored the relationship between the \acr{TANGO} and variables of children's daily social environment, and for its predictive validity, the \acr{TANGO}'s relationship with a language task six months later. Together, these studies aimed at thoroughly assessing the \acr{TANGO} as a new task to measure individual differences in gaze following.

### Aims of Study II {#aims-studyII}

[Study II](#studyII) built upon the results of [Study I](#studyI) and adopted the \acr{TANGO} to examine three research questions related to individual differences. We aimed to assess (1) how gaze following develops across the lifespan, (2) how people cognitively process gaze cues, and (3) how gaze following relates to other (social-) cognitive abilities.

To answer the first question, we remotely collected data from 3- to 80-year-olds and examined changes in their ability to follow gaze. While previous gaze following research often focused at the youngest age in which children can follow gaze [e.g., @dentremont2000perceptual; @dentremont1997demonstration], we focused on the development (in precision) after this initial milestone. As in [Study I](#studyI), children participating in the study lived in Leipzig, Germany, and either completed the study online or in their kindergartens. Adults were internationally sampled and remotely participated in the study online.

Second, we developed a computational cognitive model to explain the underlying processes of how people process gaze. We hypothesized that participants observe the pupil location within the eye and calculate gaze vectors that point toward the attentional focus. As this process was likely to be noisy, individual differences were assumed in the participant's uncertainty surrounding this gaze vector. We judged the evidence for this gaze model by comparing it to two alternative explanations of the data: a center bias and a random guessing model. Due to its underlying geometrical features, the gaze model predicted that uncertainties around the gaze vector increased the further an agent looked to the side. We planned to check for this signature pattern in the data by assessing the participants' imprecision levels in each target bin.

Third, we intended to test whether an individual's precision in gaze following related to other (social-) cognitive abilities. Consistent with our gaze model, we assessed whether gaze following was related to non-social vector following. To test this claim, we designed a new vector following task that matched the \acr{TANGO} as closely as possible but within a non-social context. The vector following task relied on the concept of magnetism and asked children to locate a magnet based on the location of a gearwheel. Furthermore, we applied four tasks from a \acr{ToM} task battery [@wellman2001metaanalysis] and two perspective-taking tasks [@flavell1981younga; @flavell1981development]. These comparisons aimed to disentangle the components that make up gaze following. In sum, [Study II](#studyII) aimed to provide a comprehensive picture of the lifelong development, cognitive processes, and components of gaze following.

### Aims of Study III {#aims-studyIII}

Studies [I](#studyI) and [II](#studyII) presented above relied on child samples from the Global North (Leipzig, Germany). Traditional developmental theories often assume that central features of social cognition hold universally true across human cultures [@wellman2013universal]. On the other hand, communities vary in how infants are typically carried and how often they interact face-to-face (see [Introduction](#intro-gaze-cc)), and thus, we might expect cross-cultural differences in how children determine another's attention and follow gaze [@akhtar2008privileging]. With [Study III](#studyIII), we aimed at evaluating the universality and variability of gaze following. To broaden our perspective, we collected data of children's gaze following abilities from 17 diverse communities spanning five different continents. To our knowledge, this attempt constituted the largest international sample on children's gaze following abilities to this date. For further information on the studied communities, the sample selection, and participant recruitment strategies, please see the online supplements of [Study III](#studyIII) (accessible under <https://github.com/ccp-eva/gafo-cc-analysis/blob/main/supplement/supplement.pdf>).

We aimed to analyze the data in three different ways. First, we examined the developmental trajectory of gaze following across communities. Second, we explored whether absolute differences in gaze following imprecision related to variables concerning the data collection mode and/or children's daily environments. Third, we checked whether the signature pattern predicted by our gaze model in [Study II](#studyII) could be found in all communities studied. With this approach, we aimed to investigate whether the same underlying model could describe how children worldwide process gaze. All in one, this study intended to provide first evidence for the universality or variability of gaze following across diverse communities.

### Aims of Study IV {#aims-studyIV}

[Study IV](#studyIV) intended to strengthen the basis for using the newly developed gaze following task in cross-cultural research. The paper had three main aims. First, we described the process of designing the cross-cultural gaze following task, the \acr{TANGO-CC}. We aimed to provide a roadmap for other researchers on how to pragmatically develop a new social cognition task that can be used for studying diverse communities.

Second, we provided a tutorial how other researchers can use and customize the \acr{TANGO-CC} according to their needs. This section aimed to highlight the components of the task that are constant and those that are variable and can be adapted to diverse languages and communities.

Third (and most importantly), we aimed to examine the \acr{TANGO-CC}'s reliability across diverse communities. While the psychometric properties of the \acr{TANGO} were previously tested in one setting (Leipzig, Germany; [Study I](#studyI)), we cannot simply generalize these findings and assume the task's validity and reliability based on a mono-cultural sample. For this purpose, we aimed to further analyze the data set from [Study III](#studyIII). We assessed performance across trial types, within- and between-community variation, and internal consistency measures in all 17 communities studied. Together, this study aimed at providing a direction of how researchers can study variation in social cognition at an individual- and community-level.

## Research Practices {#approach-practices}

In the sections above, I have highlighted the theoretical approaches and aims of the publications included in this dissertation. All of these studies build upon the same underlying testing infrastructure. As this dissertation strongly focuses on methods development, I want to outline our main methodological decisions in designing this new testing infrastructure. In-depth information regarding each specific study can be found in the corresponding manuscripts in [Appendix A](#appendixA).

### Presentation Mode {#approach-presentation}

Before designing the \acr{TANGO}, we had to choose a presentation mode for the experimental stimuli. Many traditional developmental studies have designed interactive tasks in which an experimenter or caregiver engages with the child. This makes standardization difficult as experimenters (or caregivers) have individual communication styles, might accidentally alter the instruction script due to memory gaps, or need replacement at some point (e.g., when temporary work contracts of research assistants end). In addition, this approach makes scaling data collection difficult as training experimenters requires substantial temporal and financial resources. Since studies investigating individual differences rely on large sample sizes, we decided to take another route. We designed an online testing platform that hosts studies in all common web browsers. It can be accessed on all devices (e.g., laptop, tablet) and does not require prior installation. Even though the task was programmed as a website, it does not require an internet connection (for more information, see [Programming Framework](#approach-programming) further down). The task itself is presented as an animated, interactive picture book. Audio instructions guide children through the task and describe the presented events. Trial types build up on each other and familiarize children with the response format (i.e., clicking or touching the screen).

The design as an online study has several advantages. First, it allows for maximally standardized procedures as audio instructions are pre-recorded and automated. Second, data does not need to be entered manually or coded from video. Instead, the website stores response times and participants' clicking behavior automatically. This greatly reduces potential coding biases and rater errors. Third, the presentation as a website allows for in-person and remote study participation. Families can choose whether they want to participate by coming to the research lab, or kindergartens, or whether they want to participate within the comfort of their own home. In this case, no appointments or rooms in the lab need to be scheduled. The families receive a personalized invitation link and can access the online study whenever and wherever it suits them best. This increases the inclusiveness for families with busy schedules, longer traveling distances to the lab or children who might be too shy to interact with strangers. While studies conducted in a research lab might be prone to over-study families with certain characteristics (e.g., families living closer by, having a higher SES or more free time), online studies might make study participation more accessible for a wider range of families\thinspace --\thinspace which, in turn, would increase the representativeness of the sample.

We have consciously chosen to implement an active behavioral task to circumvent issues in interpretability of implicit tasks. For example, it is unclear whether looking time measures capture children's level of surprise, attention, memory formation, or other cognitive processes, and whether they show convergent validity [@dorrenberg2018how; @aslin2007look]. While our outcome response does not directly measure underlying cognitive processes, it focuses on children's active behavior, which might translate more directly into their actions in daily life.

### Programming Framework {#approach-programming}

The online study was implemented in JavaScript (client-side functionality of the website), HTML (content), CSS (styling), and PHP (server-side functionality). Since web development is a fast-moving domain, we decided against libraries like React or full-stack frameworks like Next.js, as projects relying on frameworks often require regular monitoring. One of our goals was to create a resilient code base with minimal external dependencies to avoid breaking changes through library or framework updates. Additionally, we aimed to keep the code base as easily accessible as possible so that researchers with less programming experience could also read through and adjust the code to their needs. First and foremost, we relied on “Vanilla JavaScript” (i.e., JavaScript without a special syntax or compile step). Furthermore, a module bundler, namely Parcel (\mbox{\url{https://parceljs.org}}) and, in later projects, Webpack (\mbox{\url{https://webpack.js.org}}), tracked modules and dependencies, optimized website performance and increased the overall developer experience (e.g., by enabling a development server and hot reloading).

For animation of visual stimuli, we used \acr{GSAP}, an industry-standard, high-performance animation library (\mbox{\url{https://gsap.com}}). \acr{GSAP} is widely spread in front-end development, well documented, and easy to read so including this library increased user friendliness. Stimuli were embedded as \acr{SVG}, an XML format that describes elements in mathematical formulas. Unlike other binary image formats (e.g., JPG, PNG), \acr{SVG} exposes its structure in plain text allowing developers to manipulate and animate individual content in real time. This greatly facilitates stimulus adjustments, such as recalculating positions of objects, and adding stimuli to the composition. \acr{SVG}s ensure high resolution, consistent aspect ratios, and relative object positioning across different view ports, which is especially important for remote data collection where participants use different presentation devices.

During website development, we used the development server made available by the module bundler. This means we could test the website on our local computer and only uploaded content to the web server once the website was fully implemented. The bundler builds an output folder (in our case called "dist") that contains all website content in a compressed and optimized format. This folder is essential for both online and offline data collection. For online data collection, the dist folder gets uploaded to the web server, and the study can be accessed under its corresponding URL. For offline data collection, a live server can be installed which then hosts the dist folder locally. This is especially practical in settings with unreliable or non-existent internet connection: data collection in communities living in remote villages becomes viable. Additionally, this approach is helpful for data collection with children in (German) kindergartens as these institutions often do not have public internet connection or stable telephone reception for mobile data.

URL query parameters were used to create individualized links for participating families. This way, we could pass on information from our participant database to the study website (e.g., age of the children, language of the study, personalized gift vouchers for study compensation).

### Data Processing {#approach-dataprocessing}

After a child completes the task, the website automatically saves all responses and response times. The website stores all click data and, if desired, some additional device information (e.g., touch screen yes/no, what type and version of web browser) in a text format. During the initial development and the first published article (see [Study I](#studyI) and [Study II](#studyII)), we used JSON (JavaScript Object Notation) files commonly used for transmitting data in web applications. In later stages of the project (see [Study III](#studyIII) and [Study IV](#studyIV)), we instead used CSV (Comma-Separated Values) files as these are more commonly used among psychology researchers. In these text files, each trial is represented by one row of data. Columns depict the collected variables; for example, subject id, trial type, target location, and response. If requested, a webcam recording can be captured that films the study participation via the front camera. We implemented this feature especially for remote data collection. If caregivers consented to the webcam use, we could use the webcam recordings to ensure that indeed the children themselves carried out the task and did not get any external help. Depending on the choice of the experimenter and the data collection setup, data could be uploaded to secure servers located within the Max Planck Institute for Evolutionary Anthropology, Leipzig, Germany, or could be downloaded to the testing device (e.g., tablet or computer).

Data pre-processing was greatly simplified as the study data did not require any further response coding. Individual subject files were merged into one final data set using the programming language R. Data visualization and statistical analyses were conducted within the same program.

### Accessibility of Study Materials {#approach-accessibility}

We strongly adhered to Open Science principles in the construction of the \acr{TANGO}(-CC). The projects included in this dissertation pre-registered studies with their planned sample sizes, study procedures and analyses for hypothesis testing before data collection, as well as shared the study materials, analysis scripts and data sets after data collection. This dissertation and its included publications have published all related information in online repositories on GitHub and the Open Science Framework (links leading to specific projects can be found in the respective manuscripts in the [Appendix A](#appendixA)). By cloning the corresponding GitHub repository, motivated researchers can modify and further develop the task to their needs.

Articles were written in R Markdown which allowed us to combine continuous text and results of statistical analyses into one coherent document. The aim was to reduce the chances to accidentally copy-paste incorrect or outdated findings into the manuscript. We tracked all analysis scripts and the manuscript texts in a version-controlled manner. This enables other researchers to transparently retrace decisions and changes along the way.

As the final project, [Study IV](#studyIV) incorporated refinements that have further optimized the usability of the \acr{TANGO-CC}. While adapting the source code for cross-cultural stimulus presentation, I have refactored the code base; that is, I have improved the internal structure, readability, and maintainability of the software without altering its behavior or functionality. I have added comments to the code base using JSDoc (\mbox{\url{https://jsdoc.app}}), a markup language developed to document and annotate JavaScript source code files. Furthermore, I have collected frequently asked questions and created a manual for other researchers using the task (\mbox{\url{https://ccp-odc.eva.mpg.de/tango-cc/manual.html}}). Compared to the first version of the \acr{TANGO}, these changes served to improve the task's sustainability over time.
