# General Discussion {#discussion}

## The task itself
- social enough? still on screen, only observing 
- idea for first social interaction, where participant guides where agent looks. more like a second-person perspective
- change in framing: gaze understanding to gaze following. why?

## Modeling
- why is gafo still social if vector?
- why model needed? cc signature pattern, other interpretation than raw scores, in future incorporate more complex mental states
- why new? compared to others, only reliance on eyes not head. plus ind diff

## Cross-cultural work
- do not want to signal cc is easy or we propose parachute science 
- technology effect: yes but still ind diff in communities where touchscreen = 1
- more helpful to check relative imprecision, not absolute values within or between communities
- idea for touchscreen familiarization: bubble wrap game

## Outlook
Applying the tool: Chapter on how Gafo can be extended to answer new research questions. 

### Variations of TANGO
- gafo alien to answer why we need to integrate information from 2 eyes. probably important for side locations in tango?
- circle like clock to circumvent precision with distance diffusion
- different starting directions to avoid center bias

### Open research questions
- but also: all methods sanity checks so that now theory testing can start
- do social interactions shape social cognition abilities? we need good measures on both ends, machine learning as promising avenue 
- back to uniquely human: what about great apes? how would they perform in gafo?
- now that we can study vector following, we can also go down this path: is vector estimation needed in other social cognitive abilities? what about for example action prediction, reaching at sth?

