# General Discussion {#discussion}

## Summary of Results

### Results of Study I {#results-studyI}

In [Study I](#studyI), we have examined the \acr{TANGO} as a viable task for studying individual differences in gaze following in children and adults from the Global North. 

First, we found the \acr{TANGO} to be engaging for all age groups. Participants could complete 15 test trials within five to ten minutes. The presentation as a web app functioned smoothly across different browsers and devices, and data was reliably uploaded to the web servers. Children showed similar developmental trajectories in both versions of the task (i.e., discrete box and continuous hedge version). While the average three-year-olds were still rather imprecise in locating the target\thinspace --\thinspace in the box version, only slightly better than chance\thinspace --\thinspace children became more precise with increasing age. In neither of the versions did the children or adults reach ceiling levels in their performance. We found individual differences across all ages. For example, some of the five-year-old children were more imprecise in their gaze-following abilities than the average three-year-old. Data collected remotely without supervision closely resembled those that were collected in person.

Second, excellent psychometric properties underscored that the individual differences captured by the \acr{TANGO} were meaningful and could not be ascribed to random noise: High retest reliability estimates proved that the \acr{TANGO} did not simply capture daily fluctuations but stable ability levels across time. Age-independent \acr{GLMM}-based estimates [@rouder2019psychometrics] were higher than the previously estimated *Pearson* correlations. Internal consistency estimates also pointed to the reliability of the \acr{TANGO} and suggested that participants' performance within one session was not affected by trivial effects like exhaustion or habituation. We found that different splitting and stratification methods previously proposed by @pronk2022methods led to similar or even higher internal consistency estimates.

Third, the construct and predictive validity of the \acr{TANGO} were established by probing correlations between gaze following and concepts considered to be theoretically associated: social interactions and language abilities. Children who entered daycare at a comparably older age than their peers were more likely to be imprecise in gaze following. Although the other social interaction proxies (e.g., number and age of siblings) did not improve the model fit, the results pointed in the expected direction: the more opportunities for social interactions a child had, the more precise they were in gaze following. Additionally, the \acr{TANGO} was predictive of children's receptive vocabulary, as measured by the \acr{oREV} [@bohn2024orev] six months later, even when correcting for age.

Taken together, [Study I](#studyI) established the \acr{TANGO} as a reliable and valid measure of individual differences in gaze following.

### Results of Study II {#results-studyII}

[Study II](#studyII) showed an exemplary way in which the \acr{TANGO} (in its continuous version) can be used to answer research questions on individual differences in gaze following. 

First, we found that precision in gaze following develops throughout the lifespan. Childhood was characterized by rapid changes and children reached adult-like imprecision levels in gaze following with around ten years of age. During early adulthood, participants were most precise in their gaze-following abilities, and toward older age, precision levels slightly decreased again. Individuals differed from each other in all age groups.

Second, a cognitive model was designed to interpret individual differences in gaze following in a psychologically meaningful way. The proposed process model aimed to depict how participants infer the agent's attentional focus in the \acr{TANGO}. It assumed that participants estimate the centers of the agent's eyeball and pupil and connect those as a gaze vector (i.e., line-of-sight). The angle between this gaze vector and a vector pointing horizontally to the ground is defined as the pupil angle. Participants were assumed to integrate the information of the pupil angles (and gaze vectors) from the left and right eye. The point at which both gaze vectors meet defines the attentional focus of the agent. Estimating the pupil angles was assumed to be a noisy process. This was modeled as participants sampling estimated pupil angles from a probability distribution, which was shaped by multiplying two Normal distributions centered on the true pupil angles with equal variance. Individual differences were modeled by differing degrees of uncertainty around the pupil angle (i.e., the variance representing the width of the distribution). The development (or refinement) of gaze following was conceptualized as a decrease in uncertainty around the pupil angles, which would result in less imprecision in the \acr{TANGO}. The characteristics of the probability distribution described above resulted in the following prediction: When the agent gazed towards the side, the distribution from which the participants sampled was wider compared to when the agent gazed centrally to the ground (see Figure 2 in [Study II](#studyII)). Therefore, participants should be more imprecise when targets land further out.

The results provided substantial evidence for the proposed gaze model. In the child as well as the adult sample, the gaze model estimates correlated strongly with the data mean. Participants' imprecision levels across target bins resembled a U-shape, which matched the prediction of the gaze model: targets on the very left- or right-hand side led to the highest imprecision levels, while center targets led to a decrease in imprecision. Compared to two alternative models that explained the data by a center bias or random guessing, the gaze model was clearly favored.

As became evident, the gaze model described gaze following as a social form of vector following. We tested this proposed relationship experimentally and found that gaze following correlated moderately with a non-social vector following task. Additionally, gaze following was related to two perspective-taking tasks [@flavell1981younga; @flavell1981development] but not with other \acr{ToM} tasks [@wellman2001metaanalysis]. This suggests that gaze following comprises estimations of vectors in space and evaluating another person's point of view.

In sum, [Study II](#studyII) illustrated the continuing development of accurately interpreting another's gaze direction, along with the cognitive processes behind this ability.

### Results of Study III {#results-studyIII}

Developmental theories often (implicitly) assume that social-cognitive abilities develop and function similarly across human cultures. In [Study III](#studyIII), we experimentally tested this claim. 

First, we found that children in all 17 communities studied became substantially more precise in their gaze following as they got older. A model that assumed cross-cultural variation in average performance and developmental trajectories performed better than simpler models. Nevertheless, individuals did not cluster by community, which was shown by largely overlapping distributions. Individual differences were found in all age groups and communities.

Second, we found that the gaze model proposed in [Study II](#studyII) was applicable to every studied community. Matching the model prediction, children across all communities were more precise in locating the attentional focus of the agent when they gazed centrally compared to sideways. A model comparison with the center bias and random guessing models revealed overwhelming support for the gaze model.

Third, absolute differences in gaze-following precision could be partially explained by the data collection method. Children with no access to touchscreens were found to be less precise in the \acr{TANGO}. Yet, individual differences were still present in communities where 100% of children had access to touchscreens. Similar to [Study I](#studyI), we predicted that children with relatively more opportunities for social interaction within one community would show higher levels of gaze-following precision. However, we did not find any evidence for a relationship between gaze following and the collected demographic variables (e.g., size of household, number of children).

Overall, the findings of [Study III](#studyIII) suggested that children from diverse communities were remarkably consistent in the way they processed gaze, while individual differences were found everywhere.

### Results of Study IV {#results-studyIV}

As [Study III](#studyIII) relied on participants from diverse communities, the continuous version of the \acr{TANGO} was further developed into the \acr{TANGO-CC} by exchanging the animal stimuli for human stimuli and including 13 new instruction languages. [Study IV](#studyIV) described the design process of the \acr{TANGO-CC} and examined the psychometric grounds for its use in cross-cultural data collection. For this purpose, we re-used the data set of [Study III](#studyIII).

First, we provided a roadmap to our pragmatic approach to task development: Thoroughly assessing psychometrics of the basic \acr{TANGO} version in a German setting (see [Study I](#studyI)), while already working on the cross-cultural stimulus development and selection. The importance and added value of collaborating with local researchers and assistants was especially emphasized for creating the new stimulus set. The \acr{TANGO-CC}'s web app implementation proved highly useful in adapting the stimuli and enabling a swift data collection. Children from all over the world felt comfortable participating in the tablet study, regardless of whether they had previous touchscreen experience, and the extensive data set of [Study III](#studyIII) proved the viabilit of the \acr{TANGO-CC} for cross-cultural data collection.

Second, the manuscript visualized the customizable components of the \acr{TANGO-CC}. We featured a tutorial for how other researchers interested in using the \acr{TANGO-CC} can adjust the task to their needs.

Third, and most prominently, we established the \acr{TANGO-CC}'s psychometrics across communities. Children from all communities performed better in training trials compared to test trials. Variation within communities (i.e., individual differences) greatly outweighed variation between communities. Split-half reliability estimates were calculated following three different approaches ((1) simple odd-even split, (2) a stratification by target centrality, and (3) a model-based age correction in addition to the stratification). All three approaches yielded similar results and speak for a high internal consistency across different communities.

Altogether, these findings underline the \acr{TANGO-CC}'s suitability to study gaze following across individuals and communities.

## Research Contributions {#contributions}

The projects included in this dissertation contribute to a better understanding of child development from two different perspectives: (1) by extending our knowledge about meaningful variation in a core social-cognitive ability and (2) by providing modern, valid, reliable, and generalizable open-access tasks to other researchers. I will begin by first considering the theoretical aspects before moving on to the methodological contributions.

### Theoretical Contributions {#contributions-theory}

Our newly developed gaze-following task, the \acr{TANGO}(-CC), has enabled us to study variation in one of the most fundamental social-cognitive abilities. We have focused on (1) the lifelong development of gaze following, (2) a mechanistic explanation of the cognitive processes behind it, (3) the relationship with other (social-) cognitive abilities (vector following, \acr{ToM}, language), and (4) the universality of gaze following.

A large body of research has investigated the emergence of gaze following in infancy (for review, see @delbianco2019developmental). Yet, little was known about the further development once certain qualitative milestones are reached, for example, following gaze behind barriers or to locations behind themselves [@butterworth1991minds; @corkum1995development; @deak2000effects; @moll200412]. We could show that the precision in locating another's attentional focus does indeed increase until adolescence. By conducting [Study II](#studyII) across the lifespan, we could identify the shape of change in gaze following: A rapid improvement in early childhood with a followed sequence of stability in adulthood (with a slight decline toward old age). This underlines that gaze following\thinspace --\thinspace like probably many other (social-) cognitive abilities [e.g., @raviv2018developmental]\thinspace --\thinspace continues to develop after its initial emergence in infancy. This fits the fact that younger adults outperform older ones in their \acr{ToM} abilities and the developmental trajectory follows a U shape [@henry2013metaanalytic; @rakoczy2022foundations]. Interesting and consistent research comes from Doherty and colleagues [@doherty2015developmentally; @doherty2009rapid]. In nine different tasks (or task versions), @doherty2009rapid examined children's ability to explicitly judge what an agent is gazing at. They found that two-year-olds had difficulties passing these explicit gaze judgment tasks (verbally or by pointing), while children aged three and older showed increasing performance levels across tasks. Higher angular differences (15° vs. 10°) and a congruent head turn positively influenced children's gaze judgments, while the visual framing (i.e., distance between child and objects) did not affect their ability. The proportion of children's correct first looks and correct responses were highly correlated. The authors conclude that infants and preschoolers qualitatively differ in how they understand gaze: First, children can coarsely judge eye direction in a broader visual area, and only later children develop to perform finer gaze discriminations [@doherty2009rapid]. While the earliest instance of a social-cognitive ability might be informative for the prerequisites for this ability, studying its further development helps to illuminate where and why individuals differ from each other. At some point, most children will pass a dichotomous pass-or-fail test of gaze following. And yet, these children differ in their social cognition and interaction competencies. Studying the refinement of social-cognitive abilities will help us to find out the underlying causes of diverse real-life outcomes.

We have proposed a tool for interpreting individual differences in gaze following, specifically in the form of a computational cognitive model. While existing theories have visualized gaze following as tracing a line of sight [@anstis1969perception; @symons2004you; @todorovic2006geometrical; @yaniv1990heuristics], we have formulated this idea as a testable, well-defined mathematical model with explicit assumptions. Most importantly, we have included a conceptualization of individual differences. Our model assumes that individuals differ in their uncertainty around estimated pupil angles. This formulation also helps us to conceive development, namely as a reduction in the uncertainty around the pupil angles. The gaze model makes interesting group-level predictions. We could confirm that the distance between the agent and their focus of attention (or, in other words, the centrality) influences people's precision in gaze following. This is consistent with results showing that 4.5-year-old children [@butterworth2000how] and 6-, 8-, 10-, 14-year-olds and adults [@vida2012gradual] were more accurate in identifying central compared to peripheral targets. A carefully designed, matched, non-social vector-following task correlated with gaze following, which highlights the importance of vector estimation in gaze following. This finding fits well with other research that underlines the spatial mechanisms in joint attention [@butterworth1991minds] and pointing [@omadagain2019origin], highlighting the relevance of vector estimation in other areas of social cognition.

Developmental theories often highlight the importance of social interactions in children's social-cognitive development [e.g., @vygotsky1962thought; @vygotsky1978mind; @vygotsky1987thinking]. The hypothesis is that opportunities to observe, play, fight, and communicate with others highlight their unique mental states, which, in turn, facilitates the development of \acr{ToM} and social cognition [@perner1994theory; @peterson2000kindred; @zhang2021worse]. [Study I](#studyI) and [Study II](#studyII) contribute to this body of research. In a German sample, weak positive relationships between gaze following and demographic predictors like age of childcare entry pointed in the same direction.

Related to this is the question of how gaze following and perspective-taking are connected [@astor2022gaze]. We could show that children's visual perspective-taking abilities predicted their imprecision levels in gaze following. Other \acr{ToM} tasks did not relate to gaze following. We proposed that the cognitive processes underlying gaze following and perspective-taking might overlap as both abilities require considering another person's point of view. While other \acr{ToM} tasks often rely on this component as well, they might entail more complex meta-representational aspects. For example, this could be an understanding that mental states can be false or aspectual in nature [@rakoczy2022foundations]\thinspace --\thinspace concepts that are neither required for gaze following nor visual perspective-taking. Interestingly, @doherty2009rapid have proposed that children's emerging representational understanding of attention (as part of a \acr{ToM}) could underline the importance of eye gaze in inferring the contents of another mind, which, in turn, could trigger the improvement in eye gaze discrimination in the preschool years: "Fine gaze discrimination develops slowly because it is not easy and, until the development of theory of mind, it is not necessary" [@doherty2009rapid, p. 311].

A wide-spread notion is that gaze following supports language acquisition: Children are assumed to follow gaze to identify the referent of a new word [@bohn2022predicting; @delbianco2019developmental; @tomasello2003constructing]. For example, @brooks2005development found that infants' gaze-following abilities predicted their language comprehension half a year later. Nevertheless, @astor2022gaze have argued that the relationship between language and gaze following remains inconclusive: a substantial amount of studies reported mixed evidence, lack statistical power, or combined gaze and point following into composite measures (see Figure 3 in @astor2022gaze). We addressed these issues by specifically focusing on isolated gaze following and leveraging a large data set to increase statistical power. Indeed, imprecision in preschool children's gaze following proved to be a substantial predictor for their receptive vocabulary six months later. This result helps to conclusively settle the research question on the relationship between gaze following and language development.

The proposed cognitive gaze model has demonstrated its relevance in cross-cultural research. We found substantial differences across communities in the absolute precision of children's gaze following. Had we simply compared those absolute values, we might have interpreted the findings in a way that eye gaze is processed differently across communities. Already @innis1989should have pointed out that "different performance patterns cannot be taken as evidence for different underlying mechanisms. And, symmetrically, similar performance cannot be taken as evidence for similar mechanisms" (p. 155). Consequently, they have argued for defining the formal mechanisms that regulate and describe behavior. By applying the gaze model and checking for its predicted signature patterns in the data, we could move away from the surface-level comparison and indeed found evidence that children worldwide process gaze in similar ways\thinspace --\thinspace even though they differed in their certainty around the true pupil angles. Indeed, the gaze model might provide an exemplary framework for understanding how social cognition might be universal and yet vary [@kline2018variation]\thinspace --\thinspace a leading example to explain how "All people everywhere are different, *and* all people everywhere are the same" [@wellman2013universal, p. 69].

Taken together, the included studies underline the added value of assessing variation in social cognition and show exemplary ways in which research questions benefit from an individual differences measure adapted for cross-cultural research. For practitioners in clinical or education settings, measuring an individual's social-cognitive ability might be even more relevant as this will help to monitor and support a child's unique development.

### Methodological Contributions {#contributions-methods}

After having considered how the presented studies have deepened our theoretical knowledge of variation in social cognition, or, more specifically, gaze following, I will now turn to the methodological contributions of this work.

@beaudoin2020systematic have argued that finding appropriate social-cognitive tasks for children remains difficult: Few tasks measure the ability in question in a continuous way and/or report empirically validated psychometric information. To solve the first issue, the \acr{TANGO} exists in a categorical and continuous version which increases the flexibility for other interested researchers. Importantly, continuous here means that the experimental manipulation as well as the outcome measure are designed in a continuous format. To tackle the second challenge, we have provided a detailed psychometric analysis of the \acr{TANGO} by assessing its validity, internal consistency, and retest reliability. Importantly, the \acr{TANGO-CC} addressed the often-declared need for new tasks to assess social cognition across diverse communities. Satisfactory internal consistency estimates across 17 communities proved that the \acr{TANGO-CC} is a reliable cross-cultural gaze following measure. In comparison to traditional gaze-following tasks [e.g., @astor2020social; @byers-heinlein2021development; @gredeback2010development; @ishikawa2022physiological], the \acr{TANGO}(-CC) isolates eye movement alone and removes potential confounds with simultaneous head movements.

We have openly shared the stimulus pool and the source code of the \acr{TANGO}(-CC). First, we hope this inspires other researchers to re-use the materials in their own projects. Especially the collection of cartoon-like human faces might prove helpful in designing new social cognition tasks that can be adapted for cross-cultural data collection. An exploratory analysis (see Supplements [Study II](#studyII)) indicated that superficial stimulus modifications, such as using animal faces versus cartoon human faces, did not affect children's task performance. Second, we count on other researchers to follow this example and share their own materials according to Open Science principles. Providing psychometric information on a newly designed task and making it openly accessible will hopefully help to circumvent the "toothbrush problem" [@elson2023psychological]\thinspace --\thinspace namely that researchers are reluctant to re-use tasks of other scientists.

The \acr{TANGO}'s code base could be recycled by other researchers to adapt the testing infrastructure for future tasks. It proved to be a very useful tool for collecting data at scale. The COVID-19 pandemic underlined the importance of flexible data collection strategies. The finding that in-person and remote data collection with the \acr{TANGO} yielded similar results (see [Study I](#studyI)) justifies the advance of new online methods and adds to the growing body of literature in this domain [@bohn2021children; @bohn2021how; @frank2016using].

Two additional tasks that emerged as side projects in the context of this dissertation (see [Appendix B](#appendixB)) were designed under the same development principles and operated on very similar data collection platforms: the \acr{oREV} and the \acr{PREVIC}. The \acr{oREV} is a child-directed measure. The task presents participants with four pictures, that is, one target and three distractors (phonological, semantic, and unrelated). A verbal prompt then asks participants to select the target. The initially larger item pool of the \acr{oREV} included all 30 items of the \acr{CLT} [@haman2015designing] and added 20 additional items to increase the task's difficulty and avoid ceiling effects for older children. By using \acr{IRT}-modeling based on item difficulty and discrimination, the final item pool of the \acr{oREV} could be decreased to 22 items. With regard to reliability, stability, convergent, and discriminant validity, the final task exhibits exceptional psychometric qualities in a German sample. To complement the picture of children's language development, the \acr{PREVIC} serves as a parent-directed measure. Inspired by the \acr{CDI} for infants [@fenson2007macarthurbates; @fenson2012macarthurbates; @marchman2023macarthurbates], the \acr{PREVIC} presents caregivers with a list of words and asks them which of these words their child has already spoken. Like the \acr{oREV}, the \acr{PREVIC} initially consisted of a larger item pool of 379 words and was specifically developed for (pre)school children. By leveraging the advantages of \acr{IRT}, we created two task versions: a standardized version with a fixed number of 89 words, and an adaptive version that reduces the number of words based on the caregiver input while maintaining measurement accuracy. The \acr{PREVIC} shows highly reliable results and convergent validity in a German sample. Up to this day, both tasks, the \acr{oREV} and the \acr{PREVIC}, are available only in German. However, the construction and implementation of the testing infrastructure will ease further adaptations to different languages. Furthermore, the web app platform greatly simplified collected large data sets (\acr{oREV}: *N* = 581, \acr{PREVIC}: *N* = 1190) which is essential for an \acr{IRT}-based task construction. These two tasks show the benefit of re-using the \acr{TANGO}(-CC)'s testing infrastructure.

The web app implementation might tackle another challenge of child research: Developmental studies often report high drop-out rates, for example, because of children's fuzziness, fatigue, or lack of motivation [@slaughter2007participant]. Administering the \acr{TANGO} has proven very helpful in this regard: across communities, children tended to complete the task with ease and joy, and often even asked for a repetition. Not only did this allow for many trials per child, but it also meant that drop-out rates could be greatly reduced. @allen2024using have recently promoted games as intuitive, rewarding, engineered research environments. The authors have argued that online games enable studying various domains of cognition with the potential of higher ecological validity, increased participant diversity, cross-cultural suitability and adaptability, and large-scale data sets. Our self-made, game-like design of the \acr{TANGO}(-CC) leverages these advantages while retaining maximum experimental control.

The \acr{TANGO}(-CC)'s task design enabled a large-scale cross-cultural data collection. Adopting study designs for cross-cultural research is often time-consuming and, therefore, done for each community separately [e.g., @mehta2011validation]. The modular structure of the \acr{TANGO-CC} and the usage of \acr{SVG}s ease this process by providing customizable building blocks. Task instructions are embedded as pre-recorded audio files. This way, the training of the experimenters can be streamlined, and there is little room for experimenter errors or biases. Without these features, we could not have collected data from more than a thousand children across five different continents within a time frame of 22 months.

Finally, we want to highlight the diversity of the \acr{TANGO-CC} data set from [Study III](#studyIII). Participants lived in various kinds of social, cultural, political, and ecological systems, using different languages and subsistence styles. Previous cross-cultural research has often focused on comparing communities from the urban Global North to communities from the rural Global South [@barrett2020cognitive]. We overcame this common pitfall of a dichotomous comparison by providing a more complete, more inclusive picture of the different environments in which children grow up.

## Limitations {#limitations}

While the studies included in this dissertation have shown their strengths and unique research contributions, they must be considered against some limitations.

First of all, I want to draw attention to the modification in terminology. While [Study I](#studyI) has stated that the \acr{TANGO} measures *gaze understanding*, we have switched to the term *gaze following* in [Study II](#studyII), [Study III](#studyIII), and [Study IV](#studyIV). We have defined gaze understanding as "the ability to locate and use the attentional focus of an agent" [@prein2024tango, p. 2471] and gaze following as "turning one’s eyes in the same direction as the gaze of another agent" [@prein2024tango, p. 2471] or as "the ability to identify the attentional focus of another agent" [@prein2024measuring, p. 9]. In [Study I](#studyI), we have argued that the \acr{TANGO}'s pre-requisite is gaze following and that it not only includes this component but also an action toward the gazed-at location (i.e., clicking at the target location), which would resemble real-life situations in which we apply social information to advise our own behavior. However, a reviewer of [Study II](#studyII) questioned whether the term "gaze understanding" appropriately captures the construct that the \acr{TANGO} measures. They argued that the \acr{TANGO} mainly involves estimating gaze directions, and the cognitive and perceptual underpinnings remain unclear. The phrase "understanding" might overestimate children's ability and might imply a more representational processing than is actually needed for, or measured by, the task itself. Consequently, we have adopted the term gaze following, which is more consistent with the existing literature and does not suggest any representational processing or conceptual understanding.

Regarding the task design, it might be questioned whether the \acr{TANGO}(-CC) is "social enough". As [Study II](#studyII) showed, participants' performance in the task related to a moderate degree to their ability to estimate (non-social) vectors in space. Some scholars might question whether tasks can still be considered to measure social cognition if they rely on physical cognition abilities. I would argue that most (if not all) social-cognitive abilities comprise skills from other domains. For example, consider the classical \acr{FB} Sally-Anne change-of-location task [@baron-cohen1985does; @wimmer1983beliefs]. Here, participants need a certain level of object permanence (i.e., understanding that the ball continues to exist in the box even when it cannot be seen) and causality understanding (i.e., moving a ball has consequences for where it is located) to pass the task. Social cognition might, in general, rely on some physical-cognitive abilities\thinspace --\thinspace as @butterworth1991minds said: "What minds have in common is space" (p. 55).

Stimuli of the \acr{TANGO}(-CC) are presented on a screen, and participants do not actively engage in a participatory social interaction. Researchers have pointed out that we may process social information differently when we interact directly with others than when we simply observe them [@risko2012social; @schilbach2013secondperson]. @slaughter2003introduction have argued for differentiating between competence (i.e., how an individual responds to social-cognitive tasks in a laboratory setting) and performance (i.e., how an individual applies social-cognitive abilities to contexts in their day-to-day life). We cannot be certain that the \acr{TANGO}(-CC) qualifies to measure children's daily performance in gaze following. Yet, first evidence points in the direction that the \acr{TANGO} taps into real-life social cognition. Children's perspective-taking abilities were related to imprecision in the \acr{TANGO} but less so to a matched, non-social vector following task (in Leipzig, Germany). Additionally, the relationship to family-level demographics (e.g., age of childcare entry) suggests that the \acr{TANGO} captures a social aspect of children's development.

The proposed cognitive model of gaze following estimates an inference parameter that describes participants' uncertainty around the true pupil angles. While the model gained substantial evidence, the risk of oversimplification exists: Potentially, we have missed other parameters that comprise gaze following or explain the performance in the \acr{TANGO}. For example, a motor noise parameter could be helpful to model how accurately participants click on the location that they wanted to click. In addition, the conducted model comparisons (against a center bias and random guessing model) might profit from more complex alternative models. We have suggested a line-of-sight approach with and without motor noise in the Supplementary materials of [Study II](#studyII). While these can explain how participants solve the \acr{TANGO}, they do not model individual differences in participants' inferential abilities and do not recover the U-shaped pattern as predicted by the gaze model and as found in the data. Competitive, realistic alternative models to our gaze model remain to be established. Finally, the proposed gaze model cannot explain whether the development of increasingly precise gaze following (i.e., the decrease in imprecision in the task performance, and the decrease in uncertainty around the pupil angles in the model) appears due to physical, cognitive, or emotional changes. Physical changes might include a maturation in visual acuity (though unlikely for pre-school children), cognitive changes might include a greater sensitivity to social information or an increased comprehension that eye gaze can be used as a cue, and emotional changes might include a higher motivation to focus on other agents as children get older. These and many other factors could drive the refinement of gaze-following precision, are mutually compatible with the proposed gaze model, and need further examination.

The \acr{TANGO} allowed us to employ the same study design from early childhood into late adulthood, which eases a direct quantitative data comparison. Yet, applying the same study design does not necessarily entail capturing the same underlying constructs in all age groups. Longitudinal or developmental measurement invariance means that a task validly measures the target phenomenon at different ages to be both valid at each age and comparable across ages [@skinner2019developmental]. Factors like familiarity with the data collection method or stimuli might influence participants' performance in a task (see effect of touchscreen experience in [Study III](#studyIII)). While the developmental trajectory found in [Study II](#studyII) suggests that participants with older age had no issues completing the \acr{TANGO}, future studies should further investigate its longitudinal/developmental measure invariance [@petersen2023reexamining].

Children with no prior touchscreen access showed slightly larger imprecision levels in the \acr{TANGO-CC}. These technology effects remain important consider when applying the \acr{TANGO-CC} and interpreting the results across communities. Noticeably, communities in which all children had access to touchscreens still showed individual differences. This underlines that not all variation can be attributed to different levels of technology exposure. Additional variables that could predict children's performance in the \acr{TANGO-CC} need to be examined.

Regarding the cross-cultural gaze-following study (see [Study III](#studyIII) and [Study IV](#studyIV)), several limitations come to mind. First, the sample selection might be questioned. Selection of the included communities in [Study III](#studyIII) relied on convenience sampling and was not driven by theoretically relevant dimensions or selecting maximally different populations [@boehnke2011sampling; @nielsen2017persistent]. At worst, this could have left us missing a crucial component or axis of variation in the cognitive component that we studied [@apicella2020weird]. Furthermore, it should be noted that the samples included urban and rural communities in the Global South, while participants from the Global North all lived in urban environments. As @broesch2023roadmap highlighted, "Cross-cultural variability also exists 'at home', including in communities with different migration histories, or across regions" (p. 603)\thinspace --\thinspace and therefore, including diverse communities within the Global North could have strengthened the study's findings. Relatedly, we only measured very rough proxies of environmentally and culturally relevant factors (e.g., household size). Interpreting our findings would have benefited from a deeper understanding of each community's contextual factors [@broesch2023roadmap]. Another point of critique concerns the methodological approach of the \acr{TANGO-CC}. While the task was designed with constant input from local collaborators, the original brainstorming, organization, and implementation process was mainly based in Leipzig, Germany. Cross-cultural research would benefit from more community-based, participatory, decolonized methods development throughout all stages of the research process [@bermudez2016decolonizing; @grant2022decolonizing; @stanton2014crossing]. Finally, the choice of cross-cultural stimuli and the presentation mode can be criticized. While participants of the included communities in [Study III](#studyIII) seemed to behaviorally respond to and interpret the stimuli similarly, we could have put more effort into choosing a locally relevant target object [see @broesch2023roadmap; @kline2018variation]. A balloon might simply not be equally frequent or relevant in all studied communities. Analogously, presenting the \acr{TANGO-CC} on a computer screen might complicate the interpretation of findings across communities, as children were differentially exposed and familiar with the presentation device [@broesch2023roadmap; @hruschka2020we]. The effect of touchscreen exposure on children's imprecision in the task highlights this point. The study might have benefited from adjusting the task format and/or relying on multiple methods to measure children's gaze-following abilities [@broesch2023roadmap].

## Outlook {#outlook}

There remain many interesting research avenues that would benefit from an individual differences perspective on social cognition. I will first focus on those that could be studied by modifying the current version of the \acr{TANGO}(-CC), and then move on to broader, more theoretical research questions.

### Possible Spin-offs of the TANGO {#outlook-spinoffs}

The modular structure of the \acr{TANGO}(-CC) enables swift modifications of the stimuli and experimental design. Here, I provide first ideas on how to apply, modify, and extend the task to answer new research questions around gaze following or other related constructs.

Initially, we developed two task versions of the \acr{TANGO}, with one discrete and one continuous outcome measure (see [Study I](#studyI)). The studies that followed (see [Study II](#studyII), [Study III](#studyIII), and [Study IV](#studyIV)) all relied on the continuous task version. While the continuous version of the task shows slightly better psychometric properties (especially regarding the internal consistency, see [Study I](#studyI)), the discrete version of the \acr{TANGO} might be more helpful for other research questions. First, it is noteworthy that the task difficulty can be easily adjusted by varying the number of boxes between two and eight. With some additional programming efforts, the box version could be turned into an adaptive testing setup: Participants could start with a small number of boxes, and once they succeed in a given trial, the difficulty is adjusted and more boxes are shown. This might help implement a training intervention or study children's learning curves in gaze following. Second, the boxes in the discrete version could be modified into different colors or forefronts. The appearance of the boxes could be matched to some features of the agent: For example, a monkey and a box with a banana sticker in the front, or a girl wearing blue shorts and a t-shirt with a blue box. Phenomena such as group identity, prior knowledge, or diverse desires could be studied in this way. Another example could be action prediction, that is, the question of whether children could anticipate to which box an agent would gaze toward depending on some characteristical feature of the agent.

The youngest participants in [Study II](#studyII) (especially the three-year-olds) showed high levels of imprecision in the \acr{TANGO}. This might be due to the subtle gaze cues. Existing studies found that already three- to four-month-olds can follow gaze [e.g., @dentremont1997demonstration]. However, "It is worth noting that the accuracy of infants’ gaze localization abilities is not known. The measure used in gaze-following experiments is often no more precise than whether infants look to the correct side" [@doherty2009rapid, p. 309]. The \acr{TANGO}(-CC) could be adapted to include a head movement of the agent. Comparing the task with and without head movement would allow us to disentangle the importance/saliency of both components (i.e., eyes and head) for children's precision in locating an attentional focus.

Alternatively, younger children might have been less precise (see [Study II](#studyII)) because they were less intrinsically motivated than older participants or did not understand that precision is the task's goal. The \acr{TANGO}(-CC) could be modified to include rewards depending on a child's precision level. For example, a rewarding tune or video clip could be played. The presentation of the tune/video could become longer the more precise a child located the target. This design might (1) increase children's motivation to be precise, (2) help to keep children engaged in the task, and (3) provide a measure of children's potential learning curve in gaze following (comparing earlier with later trials). The task instructions could, furthermore, highlight that participants can take their time until they are confident in their choice. This could reduce a potential confound between faster response times and higher imprecision levels (known as speed-accuracy trade-off [@zaal2005developmental]). However, please note that in an exploratory analysis, no relationship between response time and imprecision in the \acr{TANGO} was found.

In the [Limitations section](#limitations), I have discussed whether the \acr{TANGO}(-CC) is "social enough". One idea to increase the social context of the task is to create a prior social interaction between the participant and the agent on screen. In a spin-off attempt (\mbox{\url{https://github.com/ccp-eva/gafo-cc/tree/playground}}), I have created a task version in which the participant can guide where the agent looks: The participant can click on any location on the screen, and the agent then gazes at exactly this location. While this certainly remains an interaction on screen, it does enhance the second-person perspective and may underline the shared intentionality between the agent and the participant.

Another idea to increase the social aspects of the task would be to design a joint attention version. Here, the agent could alternate their gaze between the balloon and the participant. This might underline the intention of the agent to guide the participant to the balloon location and potentially increase the participants' motivation to follow the agent's gaze. It might be worthwhile to first investigate how participants behave when the agent only shows saccade eye movement to the target location. Having the agent's gaze only shortly available to the target location might increase the \acr{TANGO}(-CC)'s difficulty.

The cognitive model of gaze following (see [Study II](#studyII)) assumes that participants integrate information of the agent's left and right eye to estimate their attentional focus. Potentially, integrating the information is especially important for the more challenging target locations to the sides. The \acr{TANGO}(-CC) could easily be adapted to test this claim. For example, the agent could be modified into a playful, alien-like appearance which would make it possible to vary the number of eyes (e.g., one vs. three eyes). This setup could help to disentangle which pupils the participants rely on to estimate the focus of attention.

Another assumption of the gaze model is that participants are biased towards the screen center. We could explore which components lead to this center bias by creating new starting scenes in the \acr{TANGO}(-CC): The position of the agent and the starting point of the balloon could be varied. For example, the agent could be positioned on the very left- or right-hand side of the scene. Furthermore, we could modify the direction of the balloon's trajectory. So far, the balloon's final position varies on the horizontal plane. We could estimate whether difficulties vary when the balloon varies on the vertical plane\thinspace --\thinspace which has been shown to develop later in gaze following [@silverstein2021infants].

Most importantly, the current version of the \acr{TANGO}(-CC) results in different distances for different target positions: the very far left and right target positions yield the longest balloon trajectories. Together with the characteristics of distributions in the gaze model, this results in the prediction that participants show greater imprecision in trials where the balloon lands sideways. An alternative setup could employ a circle-based design (G. Gredebäck, personal communication, July 14, 2022). Imagine a clock. The agent and balloon starting position would be in its center. This time, however, the balloon would fly in all possible directions like watch hands pointing at the 12 different hours. Importantly, the movement radius of the balloon would stay the same so that it always covers the same distance. This alternative design could circumvent the potential diffusion between participant precision and balloon distance, allowing us to refine the cognitive gaze model.

Lastly, a touchscreen familiarization could be completed before participants start the \acr{TANGO}(-CC). This might be especially helpful for participants with no or little technology exposure (see [Study III](#studyIII)). One idea would be implementing a bubble-wrap game where participants can crush little air pockets (or even balloons) by quickly clicking on them. This design could accustom participants to be precise, determined, motivated, and quick in their touchscreen responses. Of course, touchscreen trainings like this would benefit from the existing testing infrastructure of the \acr{TANGO}(-CC).

### Open Research Questions {#outlook-questions}

While we have successfully studied gaze following from early childhood into old age, we have relied on a cross-sectional study design. Future research could employ the \acr{TANGO}(-CC) in a longitudinal study to investigate how children develop and refine their gaze-following abilities throughout their childhood. Combining such efforts with collecting demographic variables and other (social-) cognitive abilities would result in a more fine-grained understanding of helping and hindering factors in this development.

So far, the \acr{TANGO}(-CC) has been presented as an active behavioral task. Future research could apply eye tracking with the \acr{TANGO}(-CC). This would have several advantages. First, by moving away from an active behavioral choice, younger infants could be included. This would complete the lifespan perspective from [Study II](#studyII) and enable testing the cognitive gaze model for this age group. Other research has suggested an alternative mechanism for gaze processing based on luminance [@ando2002luminanceinduced; @doherty2009rapid; @doherty2015developmentally], where the darker side of the eye (iris and pupil) compared to the bright sclera marks the perceived gaze direction. This process might be less accurate but computationally lighter, potentially explaining how infants process gaze [@doherty2009rapid; @doherty2015developmentally]. Disentangling the processing mechanisms of infants' gaze following and comparing alternative computational models remains an interesting open research area. Second, with the help of an eye-tracking study, we could compare touch and gaze behavior [see @doherty2009rapid]. This might be especially interesting for children who are imprecise in their touch behavior. Do these children look exactly where the agent is gazing and are just imprecise in their touch behavior? Or do they rather already look imprecisely and touch exactly where they themselves have followed the agent's gaze? The interplay or match between looking and touching behavior might prove helpful in identifying the sources of errors, which, in turn, would be very informative for computational modeling work [@hoffman2022catching].

Our proposed gaze model established a process-level theory of how people estimate another agent's point of attention. What it does not include is a theory on the emergence of gaze following in the first place. It remains unclear which mechanisms drive children to start following eye gaze [@astor2022gaze]. Existing theories place different emphasis on children's innate abilities [@baron-cohen1995mindblindness; @batki2000there], their social awareness, and motivation [@tomasello1999social; @meltzoff2007me; @astor2020social; @friesen2011gaze; @ishikawa2020learning], or their propensity for reinforced learning [@triesch2006gaze; @corkum1998origins; @silverstein2021infants]. Testing these theories against each other and disentangling potential driving forces in the development of gaze following remains an interesting open research avenue.

The \acr{TANGO}(-CC) focuses on detecting gaze direction, and as such, more on the participant's passive role as a gaze observer and the information-acquiring and processing perspective. However, eye gaze has been said to fulfill many different functions in social interactions: eye gaze might signal a warning, a communicative intention, or an emotional state [e.g., @argyle1973different]. Recent research by @gerlofs2022eye has started to investigate the communicative component of gaze by studying adults' looking behavior during a hide-and-seek game. Future research could investigate the developmental origins of the different gaze functions and how children decide how to direct their own gaze.

We have seen that developmental theories often assume that social interactions shape social-cognitive abilities. For example, infants are particularly responsive to contingencies experienced during daily interactions with their caregivers [@bigelow1998infants; @bigelow1999effects; @bigelow2006two; @akhtar2008privileging]. In [Study I](#studyI), we found suggestive evidence that social interaction opportunities correspond to higher precision levels in gaze following. However, this claim needs further empirical justification. Most importantly, we need good measures on both ends: for the social-cognitive abilities in question but also for children's daily social interactions. The parental questionnaire applied in [Study I](#studyI) could only serve as a rough proxy for children's daily interactions. What is needed are more fine-grained tools to capture children's lived experiences. Modern machine learning and computer vision advancements seem to be a promising avenue in this regard [@bergelson2023everyday; @donnelly2021longitudinal; @duan2017computer; @long2023babyview; @isaev2024computer; @malmir2013home; @mcmahon2023seeing]. Furthermore, we could not replicate the relationship between gaze following and the number of siblings in the cross-cultural sample (see [Study III](#studyIII)). Cross-culturally assessing these family-level variables in more detail could help to illuminate which interactions affect children's social cognition.

The relationships between gaze-following precision and language abilities, non-social vector following, and perspective taking were only assessed in a sample from the Global North (Leipzig, Germany). Future research could investigate said relationships in more diverse communities to test whether they are generalizable.

The studies included in this dissertation focus on gaze following as an important cornerstone for a child's social-cognitive development. While face-to-face interactions and eye contact are highlighted in Western culture, other communities might focus more on other social and communicative cues [@kline2018variation]. @akhtar2008privileging have cautioned to exclusively rely on gaze following as a measure of social engagement and attention/intention understanding. Similarly, @doherty2009rapid have stated that "body direction and posture, and particularly head direction, are more useful cues to engagement than is eye direction" (p. 310). Future studies should examine how other senses, like tactile and/or verbal modalities (e.g., touch, prosody, voice direction), are used across diverse communities to determine the attentional focus of another agent [@akhtar2008privileging; @kline2018variation; @wefers2023universality]. A positive example of such work comes from @bard2021joint, who have proposed a culturally inclusive concept of *joint engagement* which allows for these expressions in other modalities and with more diverse social partners and topics. Indeed, traditional visual joint attention episodes were more common in Western communities. At the same time, "triadic connectedness" was observed in infants coming from a community in the U.K., from a Nso community in Cameroon, and an Aka community in the Central African Republic [@bard2021joint].

To come back to the [Introduction](#introduction), the field of comparative studies on gaze following could be expanded to further assess the characteristics of social cognition that (arguably) make us uniquely human. Existing research has shown that great apes and other mammals can follow gaze [@rosati2009looking; @tomasello1998five; @kano2014crossspecies; for review, see @itakura2004gazefollowing]. For example, like one- to one-and-a-half-year-old human infants, chimpanzees can follow gaze to locations behind them [@povinelli1997specificity]. However, conflicting findings exist on whether non-human great apes follow gaze mainly based on the eye direction alone or a combination of head and eye movement [e.g., @povinelli1997exploitation; @tomasello2007reliance]. In addition, @itakura2004gazefollowing concluded their review by arguing that it is unclear if and which non-human great apes understand the "seeing-knowing relationship" (p. 217): In other words, understanding the eyes as a source of knowledge, and consequently, gaze as affecting mental states. To further test the great apes' understanding of gaze, the \acr{TANGO}(-CC) could be adjusted for comparative use: How would non-human great apes perform in this gaze-following task? Studies could either rely on tracking the eye gaze of the apes [e.g., @krupenye2016great] or employ a touchscreen format. Many of the chimpanzees, gorillas and orang-utans at the Wolfgang Köhler Primate Research Center in Leipzig, Germany, have gained experience with participating in touchscreen studies [@allritz2021chimpanzees; @close2015colour; @margiotoudi2019sound; @munar2015common], and the \acr{TANGO}(-CC) might prove feasible for this testing setup.

While the studies included in this dissertation focus on social cognition and gaze following, we also invented a new continuous task of non-social vector following (see [Study II](#studyII)). Having this task at hand, we could examine whether vector estimation is needed for other social-cognitive abilities. For example, predicting an action of another agent (e.g., pointing or reaching for a cup) might rely on estimating vectors in space [@omadagain2019origin]. Studying how social- and non-social cognitive abilities interact with each other will help us to disentangle the (inter) independence of our core cognitive processes.

Future studies could investigate individual differences in other, potentially more complex social-cognitive abilities. As we have seen in the [Introduction](#introduction), experts have assumed little variation in children's gaze following. The studies included in this dissertation have shown that children do vary even in this fundamental social-cognitive ability. However, the variation is clearly not about *whether* children follow gaze but *how precisely* they do so. It remains an interesting open research avenue to assess how children vary in more complex social-cognitive abilities. One example of such an ability could be how children learn to distinguish different knowledge states. A classical test of understanding knowledge access comes from @wellman2001metaanalysis: Here, children see the content of a box and need to judge whether another ignorant agent knows what is inside this box. Like the Sally-Anne \acr{FB} task, the outcome variable is dichotomous and does not leave much room for measuring children's increasingly fine-grained social cognition. In a preliminary pilot study, we have begun implementing a continuous outcome measure that captures children's sensitivity to gradual knowledge states (\acr{DISKO}; \mbox{\url{https://github.com/ccp-eva/disko}}). Children witness how an agent walks with her pet into a hut. They walk along one out of several paths that are built like a decision tree. Familiarization trials show children that the agent and the pet always want to reach the same hut. In the test trials, the agent witnesses differing amounts of the pathway that her pet is walking. For example, the agent sees her pet taking the very first turn to the left, but then a telephone rings, and the agent has to leave. The pet continues to walk the pathway into one of the huts. The agent returns and children are asked to predict to which hut the agent will go. They can distribute stickers across all options. For children that show knowledge-ignorance understanding, they should vary their sticker distribution so that it matches the epistemic state of the agent (i.e., placing no stickers on huts that the agent can exclude as the pet’s location; and equally placing sticker on the huts where her pet could be). As such, the \acr{DISKO} could measure children's action prediction in situations where the agent has gradually varying knowledge access.

Computational cognitive modeling might prove helpful in describing and predicting this social-cognitive ability. A potential model could involve two model parameters: $\beta_1$ and $\beta_2$. The parameter $\beta_1$ would capture children's sensitivity to differences in knowledge states based on differential perceptual input, and the parameter $\beta_2$ would capture how much children get biased or distorted by reality (i.e., action prediction based on the agent’s belief or the world state as in the pet's actual location). The gaze model proposed in [Study II](#studyII) could potentially serve as one of the components that make up $\beta_1$. The parameter $\beta_2$ could potentially be useful for modeling \acr{FB} understanding. This proposed study idea highlights (at least) two new research aims. First, it highlights how new study designs could measure social cognition in a more continuous, fine-grained manner so that individual differences can be captured\thinspace --\thinspace eventually building up a new social cognition task battery. Second, it underlines the appeal of modeling social cognition. Cognitive models could build up on each other and break down the components needed to master a certain ability [@baker2017rational]. Potentially, we could assess whether gaze following is, indeed, a fundamental part of other social-cognitive abilities.
