# Conclusion {#conclusion}

In this dissertation, I have questioned the traditional perspective of interpreting individual differences as measurement error or noise, and have shed new light on existing variation in social cognition. I have shown the added value of this perspective on the concrete example of gaze following across individuals, ages, and communities. The studies included in this dissertation have reported the development, psychometric assessment, and application of a new task to measure individual differences in gaze following. The extensive evaluation of the \acr{TANGO} and the \acr{TANGO-CC}, respectively, constitutes an exception in the field of social-cognitive studies. Administering the \acr{TANGO}(-CC) has enabled us to gain a comprehensive, multi-perspective view on gaze following and decipher the universal cognitive processes behind it. A computational cognitive model showed that children and adults follow gaze by estimating pupil angles and, consequently, gaze vectors that run from the center of the eye through the pupil. The development of gaze following, and behavioral differences, can be explained by varying amounts of uncertainty in this noisy inference process. The proposed gaze model could describe children's gaze following in 17 diverse communities worldwide, which speaks for a universal cognitive process in estimating gaze directions. Furthermore, gaze following related to children's receptive vocabulary, proxies of social interaction opportunities, non-social vector following and perspective-taking abilities (in a German child sample). In sum, this dissertation illustrates how combining reliable tasks, formal theoretical models, and cross-cultural research enables us to study the development and mechanisms of social cognition\thinspace --\thinspace precisely those abilities that make us arguably uniquely human.
