# Appendix A — Overview of Articles Included in the Dissertation {#appendixA}

\begin{table}[H]
\centering
\footnotesize
\begin{tabular}{p{8mm}p{55mm}p{18mm}p{48mm}p{9mm}}\toprule
Article No. & Bibliography & Publication Status & Specific Contribution & Weighing Factor \\
\midrule
1 & Prein, J. C., Kalinke, S., Haun, D. B. M.*, \& Bohn, M.* (2024). TANGO: A reliable, open-source, browser-based task to assess individual differences in gaze understanding in 3 to 5-year-old children and adults. \textit{Behavior Research Methods, 56}(3), 2469–2485. \url{https://doi.org/10.3758/s13428-023-02159-5} & Published & Co-author with predominant contribution. J.C. Prein: Conceptualization, Software, Formal Analysis, Writing-Original Draft Preparation, Writing - Review \& Editing. & 1 \\
2 & Prein, J. C., Maurits, L., Werwach, A., Haun, D. B. M.,* \& Bohn, M.* (2024). Variation in gaze following across the life span: A process-level perspective. \textit{Developmental Science, 27}(6), Article e13546. \url{https://doi.org/10.1111/desc.13546} & Published & Co-author with predominant contribution. J.C. Prein: Conceptualization, Methodology, Software, Investigation, Formal Analysis, Writing - Original Draft Preparation, Writing - Review \& Editing.  & 1 \\
3 & Bohn, M.*, Prein, J. C.*, Ayikoru, A., Bednarski, F. M., Dzabatou, A., Frank, M. C., Henderson, A. M. E., Isabella, J., Kalbitz, J., Kanngiesser, P., Keşşafoğlu, D., Koymen, B., Manrique-Hernandez, M., Magazi, S., Mújica-Manrique, L., Ohlendorf, J., Olaoba, D., Pieters, W., Pope-Caldwell, S., … Haun, D. (2024). \textit{A universal of human social cognition: Children from 17 communities process gaze in similar ways.} [Manuscript under review]. PsyArXiv. \url{https://doi.org/10.31234/osf.io/z3ahv} & Under Review & Co-author with equal contribution. J.C. Prein: Conceptualization, Methodology, Software, Investigation, Writing - Review \& Editing & 1 \\
4 & Prein, J. C., Bednarski, F. M., Dzabatou, A., Frank, M. C., Henderson, A. M. E., Kalbitz, J., Kanngiesser, P., Keşşafoğlu, D., Koymen, B., Manrique-Hernandez, M., Magazi, S., Mújica-Manrique, L., Ohlendorf, J., Olaoba, D., Pieters, W., Pope-Caldwell, S., Sen, U., Slocombe, K., Sparks, R. Z., … Bohn, M. (in press). Measuring variation in gaze following across communities, ages, and individuals – a showcase of the TANGO–CC. \textit{Advances in Methods and Practices in Psychological Science}. Link to preprint: \url{https://doi.org/10.31234/osf.io/fcq2g} & In press & Co-author with predominant contribution. J.C. Prein: Conceptualization, Formal Analysis, Methodology, Project administration, Resources, Software, Visualization, Writing - Original Draft Preparation, Writing - Review \& Editing & 1 \\
\bottomrule
\end{tabular}
\caption{\scriptsize{* denotes shared first or last authorship}}
\end{table}

## Presentation of the Articles on Conferences {-}

\begin{hangparas}{5mm}{1}
\textbf{Article No 1}: Prein, J., Bohn, M., Haun, D. (2021). Social-cognitive development from an individual differences perspective. Virtual talk presented at the 28th Conference of the European Society for Philosophy and Psychology conference in Leipzig-Online. https://philevents.org/event/show/91814

\textbf{Article No 1}: Prein, J., Bohn, M., Haun, D. (2021). Social-cognitive development from an individual differences perspective. Talk presented at the 4th Konstanz summer school on internet-based data collection and analysis. https://www.psychologie.uni-konstanz.de/en/4th-summer-school-on-internet-based-data-collection-and-analysis0/

\textbf{Article No 2}: Prein, J., Bohn, M., Haun, D. (2022). Modeling individual differences in children’s understanding of gaze cues. Virtual talk presented at the Budapest CEU Conference on Cognitive Development. https://cdc.ceu.edu/bcccd22

\textbf{Article No 2}: Prein, J., Bohn, M., Maurits, L., Haun, D. (2022). Measuring and modeling individual differences in children’s understanding of gaze cues. Poster presented at the 3rd Joint Meeting of the Society for Philosophy and Psychology \& European Society for Philosophy and Psychology in Milan. https://www.europeanspp.org/meetings.html

\textbf{Article No 2}: Prein, J., Bohn, M., Maurits, L., Kalinke, S., Haun., D. (2022). Modeling individual differences in children’s understanding of gaze cues. Poster presented at the Computational Summer school on Modeling Social and collective behavior in Konstanz. https://www.exc.uni-konstanz.de/collective-behaviour/research/education/cosmos-computational-summer-school-on-modelling-social-and-collective-behaviour/

\textbf{Article No 2}: Prein, J., Bohn, M., Haun., D. (2022). From gaze understanding to knowledge attribution: Designing tasks to measure individual differences in social cognition. Talk presented at the University of Göttingen. Personal invitation.

\textbf{Article No 3}: Prein, J., Olaoba, D., Stengelin, R., Bohn, M., Haun, D. (2023). The development of gaze understanding across (at least) 6 diverse societies. Talk presented at the Budapest CEU Conference on Cognitive Development. https://cdc.ceu.edu/bcccd23

\textbf{Article No 3}: Prein, J., Bohn, M., Maurits, L., Kalinke, S., Haun., D. (2023). Measuring individual differences in social-cognitive development. Poster presented at the 14th Dubrovnik Conference on Cognitive Science. https://ducog.cecog.eu/past-conferences

\textbf{Article No 4}: Prein, J., Stengelin, R., Haun, D., Bohn, M. (2024). TANGO-CC: A customizable open-source task to study gaze understanding across cultural settings. Lightning talk presented at the Culture Conference Zurich. https://www.comparativelinguistics.uzh.ch/en/news/2024/2024-02-9-watson.html

\end{hangparas}

\newpage

## Declaration According to § 16 of the Guideline for Cumulative Dissertations {-}

I, Julia Christin Prein, avouch that all information given in this appendix is true in each instance and overall.

&nbsp;
&nbsp; 
&nbsp;
&nbsp;

Lüneburg, 9 January 2025

&nbsp;
&nbsp; 
&nbsp;

The full texts of the included manuscripts are provided below. For the accepted articles, the published versions are provided. For articles under review/currently in press, the submitted /accepted versions are provided which are published online as pre-prints. 

\newpage

## Study I {-#studyI}
\begin{minipage}{\textwidth}
\includepdf[pages={1}, scale=0.85, offset=0 -1cm, pagecommand={}]{../papers/studyI.pdf}
\end{minipage}

\includepdf[pages={2-}, scale=0.85, pagecommand={}]{../papers/studyI.pdf}

\newpage

## Study II {-#studyII}

\begin{minipage}{\textwidth}
\includepdf[pages={1}, scale=0.85, offset=0 -1cm, pagecommand={}]{../papers/studyII.pdf}
\end{minipage}

\includepdf[pages={2-}, scale=0.85, pagecommand={}]{../papers/studyII.pdf}

\newpage

## Study III {-#studyIII}

\begin{minipage}{\textwidth}
\includepdf[pages={1}, scale=0.85, offset=0 -1cm, pagecommand={}]{../papers/studyIII.pdf}
\end{minipage}

\includepdf[pages={2-}, scale=0.85, pagecommand={}]{../papers/studyIII.pdf}

\newpage

## Study IV {-#studyIV}

\begin{minipage}{\textwidth}
\includepdf[pages={1}, scale=0.85, offset=0 -1cm, pagecommand={}]{../papers/studyIV.pdf}
\end{minipage}

\includepdf[pages={2-}, scale=0.85, pagecommand={}]{../papers/studyIV.pdf}