# Appendix B — Further Publications {-#appendixB}

The following Appendix B contains other publications that were written in the context of the dissertation but not included in the main text, with their respective abstracts.

## Action anticipation based on an agent’s epistemic state in toddlers and adults {-#manybabies}

**Citation:** Schuwerk, T., Kampis, D., Baillargeon, R., Biro, S., Bohn, M., Byers-Heinlein, K., Dörrenberg, S., Fisher, C., Franchin, L., Fulcher, T., Garbisch, I., Geraci, A., Grosse Wiesmann, C., Hamlin, K., Haun, D. B. M., Hepach, R., Hunnius, S., Hyde, D. C., Karman, P., ..., Prein, J., ... Rakoczy, H. (2021). *Action anticipation based on an agent’s epistemic state in toddlers and adults. Child Development* (In-Principle Acceptance of Registered Report Stage 1: Study Design). PsyArXiv. \mbox{\url{https://doi.org/10.31234/osf.io/x4jbm}}

**Abstract:** Do toddlers and adults engage in spontaneous Theory of Mind (ToM)? Evidence from anticipatory looking (AL) studies suggests that they do. But a growing body of failed replication studies raised questions about the paradigm’s suitability. In this multi-lab collaboration, we test the robustness of spontaneous ToM measures. We examine whether 18- to 27-month-olds’ and adults’ anticipatory looks distinguish between two basic forms of an agent’s epistemic states: knowledge and ignorance. In toddlers [ANTICIPATED n = 520 50% FEMALE] and adults [ANTICIPATED n = 408, 50% FEMALE] from diverse ethnic backgrounds, we found [SUPPORT/NO SUPPORT] for epistemic state-based action anticipation. Future research can probe whether this conclusion extends to more complex kinds of epistemic states, such as true and false beliefs.

*Please note that this abstract was written for the Registered Report and does not entail results yet. Text in square brackets indicates placeholder text to be filled in after data collection.*

\newpage

## PREVIC: An adaptive parent report measure of expressive vocabulary in children between 3 and 8 years of age {-#previc}

**Citation:** Bohn, M., Prein, J. C., Engicht, J., Haun, D., Gagarina, N., & Koch, T. (2023). *PREVIC: An adaptive parent report measure of expressive vocabulary in children between 3 and 8 years of age.* PsyArXiv. \mbox{\url{https://doi.org/10.31234/osf.io/hvncp}} 

**Abstract:** Parent report measures have proven to be a valuable research tool to study early language development. Caregivers are given a list of words and are asked which of them their child has already used. However, most available measures are not suited for children beyond infancy, come with substantial licensing costs or lack a clear psychometric foundation. Here we present the PREVIC (Parent Report of Expressive Vocabulary in Children), an open access, high quality vocabulary checklist for German-speaking children between three and eight years of age. The PREVIC was constructed leveraging the advantages of Item Response Theory: we designed a large initial item pool of 379 words and collected data from N = 1190 caregivers of children between three and eight years of age. Based on this data, we computed a range of fit indices for each item (word) and used an automated item selection algorithm to compile a final pool that contains items that a) vary in difficulty and b) fit the Rasch (one-parameter logistic) model. The resulting task is highly reliable and shows convergent validity. The IRT-based construction allowed us to design an adaptive version of the task, which substantially reduces the duration of the task while retaining measurement precision. The task -- including the adaptive version -- was implemented as a website and is freely accessible online (\mbox{\url{https://ccp-odc.eva.mpg.de/previc-demo/}}). The PREVIC fills an important gap in the toolkit of researchers interested in language development and provides an ideal starting point for the development of converging measures in other languages.

\newpage

## oREV: An item response theory-based open receptive vocabulary task for 3- to 8-year-old children {-#orev}

**Citation:** Bohn, M.\*, Prein, J.\*, Koch, T., Bee, R. M., Delikaya, B., Haun, D., & Gagarina, N. (2024). oREV: An item response theory-based open receptive vocabulary task for 3- to 8-year-old children. *Behavior Research Methods, 56*(3), 2595–2605. \mbox{\url{https://doi.org/10.3758/s13428-023-02169-3}}

**Abstract:** Individual differences in early language abilities are an important predictor of later life outcomes. High-quality, easy-access measures of language abilities are rare, especially in the preschool and primary school years. The present study describes the construction of a new receptive vocabulary task for children between 3 and 8 years of age. The task was implemented as a browser-based web application, allowing for both in-person and remote data collection via the internet. Based on data from N = 581 German-speaking children, we estimated the psychometric properties of each item in a larger initial item pool via item response modeling. We then applied an automated item selection procedure to select an optimal subset of items based on item difficulty and discrimination. The so-constructed task has 22 items and shows excellent psychometric properties with respect to reliability, stability, and convergent and discriminant validity. The construction, implementation, and item selection process described here makes it easy to extend the task or adapt it to different languages. All materials and code are freely accessible to interested researchers. The task can be used via the following website: \mbox{\url{https://ccp-odc.eva.mpg.de/orev-demo}}.

\newpage

## Validation of an open source, remote web-based eye-tracking method (WebGazer) for research in early childhood {-#manywebcams}

**Citation:** Steffan, A., Zimmer, L., Arias-Trejo, N., Bohn, M., Dal Ben, R., Flores-Coronado, M. A., Franchin, L., Garbisch, I., Grosse Wiesmann, C., Hamlin, J. K., Havron, N., Hay, J. F., Hermansen, T. K., Jakobsen, K. V., Kalinke, S., Ko, E.-S., Kulke, L., Mayor, J., Meristo, M., …, Prein, J., …, Schuwerk, T. (2024). Validation of an open source, remote web-based eye-tracking method (WebGazer) for research in early childhood. *Infancy, 29*(1), 31–55. \mbox{\url{https://doi.org/10.1111/infa.12564}}

**Abstract:** Measuring eye movements remotely via the participant's webcam promises to be an attractive methodological addition to in-person eye-tracking in the lab. However, there is a lack of systematic research comparing remote web-based eye-tracking with in-lab eye-tracking in young children. We report a multi-lab study that compared these two measures in an anticipatory looking task with toddlers using WebGazer.js and jsPsych. Results of our remotely tested sample of 18-27-month-old toddlers (N = 125) revealed that web-based eye-tracking successfully captured goal-based action predictions, although the proportion of the goal-directed anticipatory looking was lower compared to the in-lab sample (N = 70). As expected, attrition rate was substantially higher in the web-based (42%) than the in-lab sample (10%). Excluding trials based on visual inspection of the match of time-locked gaze coordinates and the participant's webcam video overlayed on the stimuli was an important preprocessing step to reduce noise in the data. We discuss the use of this remote web-based method in comparison with other current methodological innovations. Our study demonstrates that remote web-based eye-tracking can be a useful tool for testing toddlers, facilitating recruitment of larger and more diverse samples; a caveat to consider is the larger drop-out rate.
