# Selbstständigkeitserklärung {#selbststaendigkeit}

Julia Christin Prein \
[Straße Hausnummer] \
[PLZ Ort] \
[Telefon] \
[Email] \

Hiermit erkläre ich, dass ich mich noch keiner Doktorprüfung unterzogen oder mich um Zulassung zu einer solchen beworben habe. 

Ich versichere, dass die Dissertation *Rethinking Variation in Social Cognition: Gaze Following across Individuals, Ages, and Communities* in der gegenwärtigen oder einer anderen Fassung noch keiner anderen Hochschule zur Begutachtung vorgelegen hat.

Ich versichere an Eides statt, dass ich die eingereichte Dissertation *Rethinking Variation in Social Cognition: Gaze Following across Individuals, Ages, and Communities* selbstständig und ohne zulässige fremde Hilfe verfasst habe. Anderer als der von mir angegebenen Hilfsmittel und Schriften habe ich mich nicht bedient. Alle wörtlich oder sinngemäß anderen Schriften entnommenen Stellen habe ich kenntlich gemacht. Über die strafrechtlichen Folgen gemäß § 156 Strafgesetzbuch wurde ich in Kenntnis gesetzt.

&nbsp;

Hamburg, [Datum] 

&nbsp; 

[Unterschrift]
