# Acknowledgments

This dissertation rests on the shoulders of many inspiring, thought-provoking, motivating, and caring individuals. The last four years have been many different things — but definitely neither boring nor stagnant. I want to thank everyone who has accompanied me on this journey.

My motivation to work on this dissertation is greatly due to my wonderful supervisors. Manuel, I cannot thank you enough for supporting me. You have taught me to critically challenge the status quo in research and to focus my energy on improving it — pragmatically, step by step. Even though I do know that you believe there *are* stupid questions, I felt very comfortable to ask you all along the way and I have benefited a lot from your patience with me. Thanks for roughly 200 meetings that have always left me more motivated and focused than I was before. Daniel, I am so happy and proud to have been a member of the CCP team. Thank you for offering me so many unique opportunities and unforgettable memories, like traveling to conferences and Uganda. I am deeply impressed by how quickly you get a grasp of a new project and know immediately which questions to ask. Thank you for being such an approachable director and having an open door to hear about my personal struggles and have philosophical discussions. To my external supervisor, Robert: your teaching in Research Methods has turned my hate for statistics into a deep passion. Thanks for encouraging me to do a PhD, for looking into open positions, and accompanying me along the way.

Thanks to all the people who made my travels to Uganda so enjoyable. I want to express my gratitude to the members of the Budongo Families Project, especially Florence, Agnes, Joan and Joseph — for your warm welcome, all your help, hard work and heartfelt laughter. 

Thanks to the people at Leuphana who made my arrival in Lüneburg so much easier. Sebastian, thank you for making it possible for me to pursue this doctoral title. Patricia, Franziska, Nele, and (again) Manuel, thanks for the welcoming and kind atmosphere in the LüneLütten lab. I am excited about what is to come next!

I am grateful to our wonderful cohort of PhDs at the MPI. You are a remarkable group of people, and I am very happy that we could share our daily struggles with each other. Noemi, I am so glad that we got to share our office for a (way too short) period of time and successfully solved the Christmas murder mystery with Marie. Wilson, thanks for enduring our laughter through the office walls, for countless lunch breaks together, and for sharing random stories about your fieldwork (and Iceland)! Without my work wife Marie, my time during this dissertation would not have been even half as great as it has been. You have made me laugh so much, even if all I wanted to do was cry. Whatever it is that I am up to, I know you will always have my back and help me get back on my feet if I fail. I love your honesty, creativity, immense courage, charming awkwardness, and quirky sense of humor, and feel so honored that you are my friend. Thank you for being you!

My dear, dear family, I am so deeply grateful to know you by my side. Whenever I talk about individual differences, I think about you, Caro, and how we two sisters have the same parents and yet, are so different (in the very best way!!). I believe it is rare that siblings do not feel the need to compete with each other but can just love each other as they are. Thank you! To my mom, who told me right in the beginning that this journey would be a marathon and not a sprint. In some of my darker moments, you told me that even if it felt like I was about to fall, I could never — because there are so many caring people who would catch me beforehand. Thank you for always having an open home and lots of support (in the form of love, food, vacations, phone calls, and advice) for me. To my dad, thanks for showing up to Leipzig so often and establishing a little concert routine together! I believe I have learned a lot of my problem-solving skills and patience from you. Even if you do not remember saying "Mach Dinge richtig" in Caro's and my childhood, I think my dissertation has greatly benefited from this sentence. Thank you, Louis, for helping with my move to Leipzig and spontaneously catching up over coffee in Leipzig or Berlin. To my grandpa, who told me he never worried that I would find my own way. And to my grandma, for all your curiosity, play, and love for children. To the whole Gerken-Prein clan (including our furry friends) — I could not wish for a better family. Finally, we are reunited in the North.

Thank you to my amazing friends, who constantly remind me to live my life outside the office. To O74, OLAV, and Shubhangi, Schlotti, and Maló, for the cozy home we built together. All our little dance breaks, kitchen karaoke, and reading clubs made even COVID isolation fun. Thanks for your patience with my mood swings and stealing lunch boxes! Thanks to Laura, for drying my tears, always having an open ear and heart, and helping me with every single move. To Marvin, for all the long hours of deep talk and starting the whole dancing journey with me. To the Kizomba community, especially Carlos and Benedikta, for forcing me to close my eyes, shut off my brain, and relax. Thanks to Arne, for nerding about statistics and providing way too much Pfeffi. To the Osna Coxis, especially Merle, Leah, and Alissa, for all the New Year's Eves, regular video calls, big hugs and words of comfort. To Niki, for constantly reaching out, joking around, and asking me how I'm doing. To Ani, Nica, and Schlotti for a lifelong friendship, wholehearted laughter, and a traveling diary. I am so grateful to have every single one of you in my life.

And finally, Steven. You have taken over so many different roles in my life over the last four years. In the beginning, I was simply grateful for your technological support and coding enthusiasm. Thank you for pushing me beyond my levels of comfort and believing in my programming skills (... and for being my IT partner ;)). But then, coding became only one of the thousand topics that we would regularly discuss. Every morning, I looked forward to you making creepy, funny faces on our office door and having long, controversial, and nerdy conversations with you. I deeply miss you in my daily work life. And yet, I do appreciate all the changes that our relationship has gone through — through all the highs and lows. I am sincerely grateful and glad to share my life with you. It is so easy being myself around you. Thank you for the commitment, stability, honesty, relaxation, music, joy, and silly jokes that you bring into my life. Your love and support means the world to me. I cannot wait for our new adventures together in Hamburg!
